// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: idl/social.proto

package social

import (
	_ "/api"
	common "/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 聊天消息类型
type MessageType int32

const (
	MessageType_TEXT        MessageType = 0 // 文本消息
	MessageType_IMAGE       MessageType = 1 // 图片消息
	MessageType_AI_RESPONSE MessageType = 2 // AI回复
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "TEXT",
		1: "IMAGE",
		2: "AI_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"TEXT":        0,
		"IMAGE":       1,
		"AI_RESPONSE": 2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_idl_social_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_idl_social_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_idl_social_proto_rawDescGZIP(), []int{0}
}

// 关注请求
type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`               // true关注 false取消关注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_idl_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_idl_social_proto_rawDescGZIP(), []int{0}
}

func (x *FollowRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// 关注列表请求
type FollowListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowListRequest) Reset() {
	*x = FollowListRequest{}
	mi := &file_idl_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListRequest) ProtoMessage() {}

func (x *FollowListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListRequest.ProtoReflect.Descriptor instead.
func (*FollowListRequest) Descriptor() ([]byte, []int) {
	return file_idl_social_proto_rawDescGZIP(), []int{1}
}

func (x *FollowListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FollowListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FollowListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 粉丝列表请求
type FollowerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowerListRequest) Reset() {
	*x = FollowerListRequest{}
	mi := &file_idl_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerListRequest) ProtoMessage() {}

func (x *FollowerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerListRequest.ProtoReflect.Descriptor instead.
func (*FollowerListRequest) Descriptor() ([]byte, []int) {
	return file_idl_social_proto_rawDescGZIP(), []int{2}
}

func (x *FollowerListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FollowerListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FollowerListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 好友列表请求
type FriendListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListRequest) Reset() {
	*x = FriendListRequest{}
	mi := &file_idl_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListRequest) ProtoMessage() {}

func (x *FriendListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListRequest.ProtoReflect.Descriptor instead.
func (*FriendListRequest) Descriptor() ([]byte, []int) {
	return file_idl_social_proto_rawDescGZIP(), []int{3}
}

func (x *FriendListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FriendListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FriendListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 发送消息请求
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`       // 发送者ID
	ReceiverId    int64                  `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // 接收者ID (0表示AI)
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                          // 消息内容
	Type          MessageType            `protobuf:"varint,4,opt,name=type,proto3,enum=social.MessageType" json:"type,omitempty"`       // 消息类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_idl_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_idl_social_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMessageRequest) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_TEXT
}

// 获取聊天历史请求
type GetChatHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 用户ID
	PeerId        int64                  `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`       // 对方用户ID
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryRequest) Reset() {
	*x = GetChatHistoryRequest{}
	mi := &file_idl_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryRequest) ProtoMessage() {}

func (x *GetChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_idl_social_proto_rawDescGZIP(), []int{5}
}

func (x *GetChatHistoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetChatHistoryRequest) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *GetChatHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetChatHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 聊天会话请求
type ChatSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSessionRequest) Reset() {
	*x = ChatSessionRequest{}
	mi := &file_idl_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSessionRequest) ProtoMessage() {}

func (x *ChatSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSessionRequest.ProtoReflect.Descriptor instead.
func (*ChatSessionRequest) Descriptor() ([]byte, []int) {
	return file_idl_social_proto_rawDescGZIP(), []int{6}
}

func (x *ChatSessionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取未读消息请求
type GetUnreadMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadMessagesRequest) Reset() {
	*x = GetUnreadMessagesRequest{}
	mi := &file_idl_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadMessagesRequest) ProtoMessage() {}

func (x *GetUnreadMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadMessagesRequest) Descriptor() ([]byte, []int) {
	return file_idl_social_proto_rawDescGZIP(), []int{7}
}

func (x *GetUnreadMessagesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 聊天消息响应
type ChatMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId      int64                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    int64                  `protobuf:"varint,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type          MessageType            `protobuf:"varint,6,opt,name=type,proto3,enum=social.MessageType" json:"type,omitempty"`
	IsAi          bool                   `protobuf:"varint,7,opt,name=is_ai,json=isAi,proto3" json:"is_ai,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageResponse) Reset() {
	*x = ChatMessageResponse{}
	mi := &file_idl_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageResponse) ProtoMessage() {}

func (x *ChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageResponse.ProtoReflect.Descriptor instead.
func (*ChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_idl_social_proto_rawDescGZIP(), []int{8}
}

func (x *ChatMessageResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChatMessageResponse) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatMessageResponse) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *ChatMessageResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessageResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ChatMessageResponse) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_TEXT
}

func (x *ChatMessageResponse) GetIsAi() bool {
	if x != nil {
		return x.IsAi
	}
	return false
}

var File_idl_social_proto protoreflect.FileDescriptor

const file_idl_social_proto_rawDesc = "" +
	"\n" +
	"\x10idl/social.proto\x12\x06social\x1a\x10idl/common.proto\x1a\ridl/api.proto\"@\n" +
	"\rFollowRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\"]\n" +
	"\x11FollowListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"_\n" +
	"\x13FollowerListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"]\n" +
	"\x11FriendListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"\x95\x01\n" +
	"\x12SendMessageRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\x03R\n" +
	"receiverId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.social.MessageTypeR\x04type\"z\n" +
	"\x15GetChatHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\x03R\x06peerId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"-\n" +
	"\x12ChatSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"3\n" +
	"\x18GetUnreadMessagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xd9\x01\n" +
	"\x13ChatMessageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x03 \x01(\x03R\n" +
	"receiverId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12'\n" +
	"\x04type\x18\x06 \x01(\x0e2\x13.social.MessageTypeR\x04type\x12\x13\n" +
	"\x05is_ai\x18\a \x01(\bR\x04isAi*3\n" +
	"\vMessageType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\x0f\n" +
	"\vAI_RESPONSE\x10\x022\xc0\x01\n" +
	"\x11FollowAuthService\x12O\n" +
	"\fFollowAction\x12\x15.social.FollowRequest\x1a\x16.common.CommonResponse\"\x10\xd2\xc1\x18\f/api/follows\x12Z\n" +
	"\rGetFriendList\x12\x19.social.FriendListRequest\x1a\x16.common.CommonResponse\"\x16\xca\xc1\x18\x12/api/users/friends2\xe8\x01\n" +
	"\x13FollowPublicService\x12f\n" +
	"\rGetFollowList\x12\x19.social.FollowListRequest\x1a\x16.common.CommonResponse\"\"\xca\xc1\x18\x1e/api/users/:user_id/followings\x12i\n" +
	"\x0fGetFollowerList\x12\x1b.social.FollowerListRequest\x1a\x16.common.CommonResponse\"!\xca\xc1\x18\x1d/api/users/:user_id/followers2\x88\x03\n" +
	"\vChatService\x12U\n" +
	"\vSendMessage\x12\x1a.social.SendMessageRequest\x1a\x16.common.CommonResponse\"\x12\xd2\xc1\x18\x0e/api/chat/send\x12^\n" +
	"\x0eGetChatHistory\x12\x1d.social.GetChatHistoryRequest\x1a\x16.common.CommonResponse\"\x15\xca\xc1\x18\x11/api/chat/history\x12]\n" +
	"\x0fGetChatSessions\x12\x1a.social.ChatSessionRequest\x1a\x16.common.CommonResponse\"\x16\xca\xc1\x18\x12/api/chat/sessions\x12c\n" +
	"\x11GetUnreadMessages\x12 .social.GetUnreadMessagesRequest\x1a\x16.common.CommonResponse\"\x14\xca\xc1\x18\x10/api/chat/unreadB\tZ\a/socialb\x06proto3"

var (
	file_idl_social_proto_rawDescOnce sync.Once
	file_idl_social_proto_rawDescData []byte
)

func file_idl_social_proto_rawDescGZIP() []byte {
	file_idl_social_proto_rawDescOnce.Do(func() {
		file_idl_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_social_proto_rawDesc), len(file_idl_social_proto_rawDesc)))
	})
	return file_idl_social_proto_rawDescData
}

var file_idl_social_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_idl_social_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_idl_social_proto_goTypes = []any{
	(MessageType)(0),                 // 0: social.MessageType
	(*FollowRequest)(nil),            // 1: social.FollowRequest
	(*FollowListRequest)(nil),        // 2: social.FollowListRequest
	(*FollowerListRequest)(nil),      // 3: social.FollowerListRequest
	(*FriendListRequest)(nil),        // 4: social.FriendListRequest
	(*SendMessageRequest)(nil),       // 5: social.SendMessageRequest
	(*GetChatHistoryRequest)(nil),    // 6: social.GetChatHistoryRequest
	(*ChatSessionRequest)(nil),       // 7: social.ChatSessionRequest
	(*GetUnreadMessagesRequest)(nil), // 8: social.GetUnreadMessagesRequest
	(*ChatMessageResponse)(nil),      // 9: social.ChatMessageResponse
	(*common.CommonResponse)(nil),    // 10: common.CommonResponse
}
var file_idl_social_proto_depIdxs = []int32{
	0,  // 0: social.SendMessageRequest.type:type_name -> social.MessageType
	0,  // 1: social.ChatMessageResponse.type:type_name -> social.MessageType
	1,  // 2: social.FollowAuthService.FollowAction:input_type -> social.FollowRequest
	4,  // 3: social.FollowAuthService.GetFriendList:input_type -> social.FriendListRequest
	2,  // 4: social.FollowPublicService.GetFollowList:input_type -> social.FollowListRequest
	3,  // 5: social.FollowPublicService.GetFollowerList:input_type -> social.FollowerListRequest
	5,  // 6: social.ChatService.SendMessage:input_type -> social.SendMessageRequest
	6,  // 7: social.ChatService.GetChatHistory:input_type -> social.GetChatHistoryRequest
	7,  // 8: social.ChatService.GetChatSessions:input_type -> social.ChatSessionRequest
	8,  // 9: social.ChatService.GetUnreadMessages:input_type -> social.GetUnreadMessagesRequest
	10, // 10: social.FollowAuthService.FollowAction:output_type -> common.CommonResponse
	10, // 11: social.FollowAuthService.GetFriendList:output_type -> common.CommonResponse
	10, // 12: social.FollowPublicService.GetFollowList:output_type -> common.CommonResponse
	10, // 13: social.FollowPublicService.GetFollowerList:output_type -> common.CommonResponse
	10, // 14: social.ChatService.SendMessage:output_type -> common.CommonResponse
	10, // 15: social.ChatService.GetChatHistory:output_type -> common.CommonResponse
	10, // 16: social.ChatService.GetChatSessions:output_type -> common.CommonResponse
	10, // 17: social.ChatService.GetUnreadMessages:output_type -> common.CommonResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_idl_social_proto_init() }
func file_idl_social_proto_init() {
	if File_idl_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_social_proto_rawDesc), len(file_idl_social_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_idl_social_proto_goTypes,
		DependencyIndexes: file_idl_social_proto_depIdxs,
		EnumInfos:         file_idl_social_proto_enumTypes,
		MessageInfos:      file_idl_social_proto_msgTypes,
	}.Build()
	File_idl_social_proto = out.File
	file_idl_social_proto_goTypes = nil
	file_idl_social_proto_depIdxs = nil
}
