// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: idl/social.proto

package social

import (
	common "/common"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FollowAuthService_FollowAction_FullMethodName  = "/social.FollowAuthService/FollowAction"
	FollowAuthService_GetFriendList_FullMethodName = "/social.FollowAuthService/GetFriendList"
)

// FollowAuthServiceClient is the client API for FollowAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 关注认证服务
type FollowAuthServiceClient interface {
	// 关注/取消关注
	// @router /api/follows [POST]
	FollowAction(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
	// 获取好友列表
	// @router /api/users/friends [GET]
	GetFriendList(ctx context.Context, in *FriendListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
}

type followAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFollowAuthServiceClient(cc grpc.ClientConnInterface) FollowAuthServiceClient {
	return &followAuthServiceClient{cc}
}

func (c *followAuthServiceClient) FollowAction(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, FollowAuthService_FollowAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followAuthServiceClient) GetFriendList(ctx context.Context, in *FriendListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, FollowAuthService_GetFriendList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FollowAuthServiceServer is the server API for FollowAuthService service.
// All implementations must embed UnimplementedFollowAuthServiceServer
// for forward compatibility.
//
// 关注认证服务
type FollowAuthServiceServer interface {
	// 关注/取消关注
	// @router /api/follows [POST]
	FollowAction(context.Context, *FollowRequest) (*common.CommonResponse, error)
	// 获取好友列表
	// @router /api/users/friends [GET]
	GetFriendList(context.Context, *FriendListRequest) (*common.CommonResponse, error)
	mustEmbedUnimplementedFollowAuthServiceServer()
}

// UnimplementedFollowAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFollowAuthServiceServer struct{}

func (UnimplementedFollowAuthServiceServer) FollowAction(context.Context, *FollowRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowAction not implemented")
}
func (UnimplementedFollowAuthServiceServer) GetFriendList(context.Context, *FriendListRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriendList not implemented")
}
func (UnimplementedFollowAuthServiceServer) mustEmbedUnimplementedFollowAuthServiceServer() {}
func (UnimplementedFollowAuthServiceServer) testEmbeddedByValue()                           {}

// UnsafeFollowAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FollowAuthServiceServer will
// result in compilation errors.
type UnsafeFollowAuthServiceServer interface {
	mustEmbedUnimplementedFollowAuthServiceServer()
}

func RegisterFollowAuthServiceServer(s grpc.ServiceRegistrar, srv FollowAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedFollowAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FollowAuthService_ServiceDesc, srv)
}

func _FollowAuthService_FollowAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowAuthServiceServer).FollowAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowAuthService_FollowAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowAuthServiceServer).FollowAction(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowAuthService_GetFriendList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowAuthServiceServer).GetFriendList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowAuthService_GetFriendList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowAuthServiceServer).GetFriendList(ctx, req.(*FriendListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FollowAuthService_ServiceDesc is the grpc.ServiceDesc for FollowAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FollowAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.FollowAuthService",
	HandlerType: (*FollowAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FollowAction",
			Handler:    _FollowAuthService_FollowAction_Handler,
		},
		{
			MethodName: "GetFriendList",
			Handler:    _FollowAuthService_GetFriendList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/social.proto",
}

const (
	FollowPublicService_GetFollowList_FullMethodName   = "/social.FollowPublicService/GetFollowList"
	FollowPublicService_GetFollowerList_FullMethodName = "/social.FollowPublicService/GetFollowerList"
)

// FollowPublicServiceClient is the client API for FollowPublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 关注公共服务
type FollowPublicServiceClient interface {
	// 获取关注列表
	// @router /api/users/:user_id/followings [GET]
	GetFollowList(ctx context.Context, in *FollowListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
	// 获取粉丝列表
	// @router /api/users/:user_id/followers [GET]
	GetFollowerList(ctx context.Context, in *FollowerListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
}

type followPublicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFollowPublicServiceClient(cc grpc.ClientConnInterface) FollowPublicServiceClient {
	return &followPublicServiceClient{cc}
}

func (c *followPublicServiceClient) GetFollowList(ctx context.Context, in *FollowListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, FollowPublicService_GetFollowList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followPublicServiceClient) GetFollowerList(ctx context.Context, in *FollowerListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, FollowPublicService_GetFollowerList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FollowPublicServiceServer is the server API for FollowPublicService service.
// All implementations must embed UnimplementedFollowPublicServiceServer
// for forward compatibility.
//
// 关注公共服务
type FollowPublicServiceServer interface {
	// 获取关注列表
	// @router /api/users/:user_id/followings [GET]
	GetFollowList(context.Context, *FollowListRequest) (*common.CommonResponse, error)
	// 获取粉丝列表
	// @router /api/users/:user_id/followers [GET]
	GetFollowerList(context.Context, *FollowerListRequest) (*common.CommonResponse, error)
	mustEmbedUnimplementedFollowPublicServiceServer()
}

// UnimplementedFollowPublicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFollowPublicServiceServer struct{}

func (UnimplementedFollowPublicServiceServer) GetFollowList(context.Context, *FollowListRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowList not implemented")
}
func (UnimplementedFollowPublicServiceServer) GetFollowerList(context.Context, *FollowerListRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowerList not implemented")
}
func (UnimplementedFollowPublicServiceServer) mustEmbedUnimplementedFollowPublicServiceServer() {}
func (UnimplementedFollowPublicServiceServer) testEmbeddedByValue()                             {}

// UnsafeFollowPublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FollowPublicServiceServer will
// result in compilation errors.
type UnsafeFollowPublicServiceServer interface {
	mustEmbedUnimplementedFollowPublicServiceServer()
}

func RegisterFollowPublicServiceServer(s grpc.ServiceRegistrar, srv FollowPublicServiceServer) {
	// If the following call panics, it indicates UnimplementedFollowPublicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FollowPublicService_ServiceDesc, srv)
}

func _FollowPublicService_GetFollowList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowPublicServiceServer).GetFollowList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowPublicService_GetFollowList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowPublicServiceServer).GetFollowList(ctx, req.(*FollowListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowPublicService_GetFollowerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowPublicServiceServer).GetFollowerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowPublicService_GetFollowerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowPublicServiceServer).GetFollowerList(ctx, req.(*FollowerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FollowPublicService_ServiceDesc is the grpc.ServiceDesc for FollowPublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FollowPublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.FollowPublicService",
	HandlerType: (*FollowPublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFollowList",
			Handler:    _FollowPublicService_GetFollowList_Handler,
		},
		{
			MethodName: "GetFollowerList",
			Handler:    _FollowPublicService_GetFollowerList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/social.proto",
}

const (
	ChatService_SendMessage_FullMethodName       = "/social.ChatService/SendMessage"
	ChatService_GetChatHistory_FullMethodName    = "/social.ChatService/GetChatHistory"
	ChatService_GetChatSessions_FullMethodName   = "/social.ChatService/GetChatSessions"
	ChatService_GetUnreadMessages_FullMethodName = "/social.ChatService/GetUnreadMessages"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 聊天服务
type ChatServiceClient interface {
	// 发送消息
	// @router /api/chat/send [POST]
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
	// 获取聊天历史
	// @router /api/chat/history [GET]
	GetChatHistory(ctx context.Context, in *GetChatHistoryRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
	// 获取聊天会话列表
	// @router /api/chat/sessions [GET]
	GetChatSessions(ctx context.Context, in *ChatSessionRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
	// 获取未读消息（用户上线时调用）
	// @router /api/chat/unread [GET]
	GetUnreadMessages(ctx context.Context, in *GetUnreadMessagesRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, ChatService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetChatHistory(ctx context.Context, in *GetChatHistoryRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, ChatService_GetChatHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetChatSessions(ctx context.Context, in *ChatSessionRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, ChatService_GetChatSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetUnreadMessages(ctx context.Context, in *GetUnreadMessagesRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, ChatService_GetUnreadMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
//
// 聊天服务
type ChatServiceServer interface {
	// 发送消息
	// @router /api/chat/send [POST]
	SendMessage(context.Context, *SendMessageRequest) (*common.CommonResponse, error)
	// 获取聊天历史
	// @router /api/chat/history [GET]
	GetChatHistory(context.Context, *GetChatHistoryRequest) (*common.CommonResponse, error)
	// 获取聊天会话列表
	// @router /api/chat/sessions [GET]
	GetChatSessions(context.Context, *ChatSessionRequest) (*common.CommonResponse, error)
	// 获取未读消息（用户上线时调用）
	// @router /api/chat/unread [GET]
	GetUnreadMessages(context.Context, *GetUnreadMessagesRequest) (*common.CommonResponse, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) SendMessage(context.Context, *SendMessageRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChatServiceServer) GetChatHistory(context.Context, *GetChatHistoryRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatHistory not implemented")
}
func (UnimplementedChatServiceServer) GetChatSessions(context.Context, *ChatSessionRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatSessions not implemented")
}
func (UnimplementedChatServiceServer) GetUnreadMessages(context.Context, *GetUnreadMessagesRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnreadMessages not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call panics, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetChatHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetChatHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetChatHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetChatHistory(ctx, req.(*GetChatHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetChatSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetChatSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetChatSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetChatSessions(ctx, req.(*ChatSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetUnreadMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetUnreadMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetUnreadMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetUnreadMessages(ctx, req.(*GetUnreadMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _ChatService_SendMessage_Handler,
		},
		{
			MethodName: "GetChatHistory",
			Handler:    _ChatService_GetChatHistory_Handler,
		},
		{
			MethodName: "GetChatSessions",
			Handler:    _ChatService_GetChatSessions_Handler,
		},
		{
			MethodName: "GetUnreadMessages",
			Handler:    _ChatService_GetUnreadMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/social.proto",
}
