// Code generated by hertz generator.

package social

import (
	"context"

	"github.com/ZOEKOFK/video_web_v3/app/pb/common"
	"github.com/ZOEKOFK/video_web_v3/app/pb/social"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// SendMessage .
// @router /api/chat/send [POST]
func SendMessage(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.SendMessageRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.CommonResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetChatHistory .
// @router /api/chat/history [GET]
func GetChatHistory(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.GetChatHistoryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.CommonResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetChatSessions .
// @router /api/chat/sessions [GET]
func GetChatSessions(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.ChatSessionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.CommonResponse)

	c.JSON(consts.StatusOK, resp)
}
