// Code generated by hertz generator.

package social

import (
	"context"
	"log"
	"net/http"
	"strconv"

	"github.com/ZOEKOFK/video_web_v3/api_gateway/client"
	commonpb "github.com/ZOEKOFK/video_web_v3/app/pb/common"
	socialpb "github.com/ZOEKOFK/video_web_v3/app/pb/social"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetFollowList .
// @router /api/users/:user_id/followings [GET]
func GetFollowList(ctx context.Context, c *app.RequestContext) {
	userIDStr := c.Param("user_id")
	userID, err := strconv.ParseInt(userIDStr, 10, 64)
	if err != nil {
		c.JSON(consts.StatusBadRequest, client.FailResponse("invalid user_id", commonpb.ErrorCode_PARAM_ERROR))
		return
	}

	var req socialpb.FollowListRequest
	if err := c.BindAndValidate(&req); err != nil {
		log.Printf("[GetFollowList] 参数绑定失败: %v", err)
		c.JSON(consts.StatusBadRequest, client.FailResponse(err.Error(), commonpb.ErrorCode_PARAM_ERROR))
		return
	}
	req.UserId = userID

	log.Printf("[GetFollowList] userID=%d, page=%d, pageSize=%d", req.UserId, req.Page, req.PageSize)

	resp, err := client.FollowPublicClient.GetFollowList(ctx, &req)
	if err != nil {
		log.Printf("[GetFollowList] gRPC 调用失败: %v", err)
		c.JSON(http.StatusInternalServerError, client.FailResponse(err.Error(), commonpb.ErrorCode_PROGRESS_ERROR))
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// GetFollowerList .
// @router /api/users/:user_id/followers [GET]
func GetFollowerList(ctx context.Context, c *app.RequestContext) {
	userIDStr := c.Param("user_id")
	userID, err := strconv.ParseInt(userIDStr, 10, 64)
	if err != nil {
		c.JSON(consts.StatusBadRequest, client.FailResponse("invalid user_id", commonpb.ErrorCode_PARAM_ERROR))
		return
	}

	var req socialpb.FollowerListRequest
	if err := c.BindAndValidate(&req); err != nil {
		log.Printf("[GetFollowerList] 参数绑定失败: %v", err)
		c.JSON(consts.StatusBadRequest, client.FailResponse(err.Error(), commonpb.ErrorCode_PARAM_ERROR))
		return
	}
	req.UserId = userID

	log.Printf("[GetFollowerList] userID=%d, page=%d, pageSize=%d", req.UserId, req.Page, req.PageSize)

	resp, err := client.FollowPublicClient.GetFollowerList(ctx, &req)
	if err != nil {
		log.Printf("[GetFollowerList] gRPC 调用失败: %v", err)
		c.JSON(http.StatusInternalServerError, client.FailResponse(err.Error(), commonpb.ErrorCode_PROGRESS_ERROR))
		return
	}

	c.JSON(consts.StatusOK, resp)
}
