// Code generated by hertz generator.

package social

import (
	"context"
	"log"
	"net/http"

	"github.com/ZOEKOFK/video_web_v3/api_gateway/client"
	"github.com/ZOEKOFK/video_web_v3/api_gateway/my_jwt"
	commonpb "github.com/ZOEKOFK/video_web_v3/app/pb/common"
	socialpb "github.com/ZOEKOFK/video_web_v3/app/pb/social"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// FollowAction .
// @router /api/follows [POST]
func FollowAction(ctx context.Context, c *app.RequestContext) {
	userID, err := my_jwt.GetUserIDFromToken(ctx, c)
	if err != nil {
		log.Printf("token提取用户 ID 失败: %v", err)
		c.JSON(consts.StatusUnauthorized, client.FailResponse("invalid token", commonpb.ErrorCode_USER_NOT_LOGIN))
		return
	}
	var req socialpb.FollowRequest
	if err := c.Bind(&req); err != nil {
		log.Printf("参数绑定失败: %v", err)
		c.JSON(consts.StatusBadRequest, client.FailResponse(err.Error(), commonpb.ErrorCode_PARAM_ERROR))
		return
	}
	log.Println(req.Status, req.UserId)
	ctxWithUserID := client.WithUserID(ctx, userID)

	resp, err := client.FollowAuthServiceClient.FollowAction(ctxWithUserID, &req)
	log.Println(resp)
	if err != nil {
		log.Printf("gRPC调用失败: %v", err)
		c.JSON(http.StatusInternalServerError, client.FailResponse(err.Error(), commonpb.ErrorCode_PROGRESS_ERROR))
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// GetFriendList .
// @router /api/users/friends [GET]
func GetFriendList(ctx context.Context, c *app.RequestContext) {
	userID, err := my_jwt.GetUserIDFromToken(ctx, c)
	if err != nil {
		log.Printf("token提取用户 ID 失败: %v", err)
		c.JSON(consts.StatusUnauthorized, client.FailResponse("invalid token", commonpb.ErrorCode_USER_NOT_LOGIN))
		return
	}
	req := socialpb.FriendListRequest{}
	err = c.Bind(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, client.FailResponse(err.Error(), commonpb.ErrorCode_PARAM_ERROR))
		return
	}
	ctxWithUserID := client.WithUserID(ctx, userID)
	resp, err := client.FollowAuthServiceClient.GetFriendList(ctxWithUserID, &req)
	if err != nil {
		c.JSON(http.StatusInternalServerError, client.FailResponse(err.Error(), commonpb.ErrorCode_PROGRESS_ERROR))
		return
	}
	c.JSON(consts.StatusOK, resp)
}
