// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: idl/users.proto

package users

import (
	common "github.com/ZOEKOFK/video_web_v3/app/pb/common"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserPublicService_Register_FullMethodName = "/users.UserPublicService/Register"
	UserPublicService_Login_FullMethodName    = "/users.UserPublicService/Login"
)

// UserPublicServiceClient is the client API for UserPublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserPublicServiceClient interface {
	// 注册
	Register(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
	// 登录
	Login(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
}

type userPublicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserPublicServiceClient(cc grpc.ClientConnInterface) UserPublicServiceClient {
	return &userPublicServiceClient{cc}
}

func (c *userPublicServiceClient) Register(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, UserPublicService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userPublicServiceClient) Login(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, UserPublicService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserPublicServiceServer is the server API for UserPublicService service.
// All implementations must embed UnimplementedUserPublicServiceServer
// for forward compatibility.
type UserPublicServiceServer interface {
	// 注册
	Register(context.Context, *UserRegisterRequest) (*common.CommonResponse, error)
	// 登录
	Login(context.Context, *UserLoginRequest) (*common.CommonResponse, error)
	mustEmbedUnimplementedUserPublicServiceServer()
}

// UnimplementedUserPublicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserPublicServiceServer struct{}

func (UnimplementedUserPublicServiceServer) Register(context.Context, *UserRegisterRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedUserPublicServiceServer) Login(context.Context, *UserLoginRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserPublicServiceServer) mustEmbedUnimplementedUserPublicServiceServer() {}
func (UnimplementedUserPublicServiceServer) testEmbeddedByValue()                           {}

// UnsafeUserPublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserPublicServiceServer will
// result in compilation errors.
type UnsafeUserPublicServiceServer interface {
	mustEmbedUnimplementedUserPublicServiceServer()
}

func RegisterUserPublicServiceServer(s grpc.ServiceRegistrar, srv UserPublicServiceServer) {
	// If the following call panics, it indicates UnimplementedUserPublicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserPublicService_ServiceDesc, srv)
}

func _UserPublicService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserPublicServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserPublicService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserPublicServiceServer).Register(ctx, req.(*UserRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserPublicService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserPublicServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserPublicService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserPublicServiceServer).Login(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserPublicService_ServiceDesc is the grpc.ServiceDesc for UserPublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserPublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.UserPublicService",
	HandlerType: (*UserPublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _UserPublicService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserPublicService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/users.proto",
}

const (
	UserAuthService_GetUserInfo_FullMethodName  = "/users.UserAuthService/GetUserInfo"
	UserAuthService_UploadAvatar_FullMethodName = "/users.UserAuthService/UploadAvatar"
	UserAuthService_GetMFACode_FullMethodName   = "/users.UserAuthService/GetMFACode"
	UserAuthService_BindMFA_FullMethodName      = "/users.UserAuthService/BindMFA"
)

// UserAuthServiceClient is the client API for UserAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 用户认证服务
type UserAuthServiceClient interface {
	// 获取用户信息
	GetUserInfo(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
	// 上传头像
	UploadAvatar(ctx context.Context, in *UploadAvatarRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
	// 获取 MFA 二维码
	GetMFACode(ctx context.Context, in *GetMFACodeRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
	// 绑定 MFA
	BindMFA(ctx context.Context, in *BindMFARequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
}

type userAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserAuthServiceClient(cc grpc.ClientConnInterface) UserAuthServiceClient {
	return &userAuthServiceClient{cc}
}

func (c *userAuthServiceClient) GetUserInfo(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, UserAuthService_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthServiceClient) UploadAvatar(ctx context.Context, in *UploadAvatarRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, UserAuthService_UploadAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthServiceClient) GetMFACode(ctx context.Context, in *GetMFACodeRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, UserAuthService_GetMFACode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthServiceClient) BindMFA(ctx context.Context, in *BindMFARequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, UserAuthService_BindMFA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAuthServiceServer is the server API for UserAuthService service.
// All implementations must embed UnimplementedUserAuthServiceServer
// for forward compatibility.
//
// 用户认证服务
type UserAuthServiceServer interface {
	// 获取用户信息
	GetUserInfo(context.Context, *common.IDRequest) (*common.CommonResponse, error)
	// 上传头像
	UploadAvatar(context.Context, *UploadAvatarRequest) (*common.CommonResponse, error)
	// 获取 MFA 二维码
	GetMFACode(context.Context, *GetMFACodeRequest) (*common.CommonResponse, error)
	// 绑定 MFA
	BindMFA(context.Context, *BindMFARequest) (*common.CommonResponse, error)
	mustEmbedUnimplementedUserAuthServiceServer()
}

// UnimplementedUserAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserAuthServiceServer struct{}

func (UnimplementedUserAuthServiceServer) GetUserInfo(context.Context, *common.IDRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUserAuthServiceServer) UploadAvatar(context.Context, *UploadAvatarRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadAvatar not implemented")
}
func (UnimplementedUserAuthServiceServer) GetMFACode(context.Context, *GetMFACodeRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMFACode not implemented")
}
func (UnimplementedUserAuthServiceServer) BindMFA(context.Context, *BindMFARequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindMFA not implemented")
}
func (UnimplementedUserAuthServiceServer) mustEmbedUnimplementedUserAuthServiceServer() {}
func (UnimplementedUserAuthServiceServer) testEmbeddedByValue()                         {}

// UnsafeUserAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserAuthServiceServer will
// result in compilation errors.
type UnsafeUserAuthServiceServer interface {
	mustEmbedUnimplementedUserAuthServiceServer()
}

func RegisterUserAuthServiceServer(s grpc.ServiceRegistrar, srv UserAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedUserAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserAuthService_ServiceDesc, srv)
}

func _UserAuthService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuthService_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServiceServer).GetUserInfo(ctx, req.(*common.IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuthService_UploadAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServiceServer).UploadAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuthService_UploadAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServiceServer).UploadAvatar(ctx, req.(*UploadAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuthService_GetMFACode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMFACodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServiceServer).GetMFACode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuthService_GetMFACode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServiceServer).GetMFACode(ctx, req.(*GetMFACodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuthService_BindMFA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindMFARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServiceServer).BindMFA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuthService_BindMFA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServiceServer).BindMFA(ctx, req.(*BindMFARequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserAuthService_ServiceDesc is the grpc.ServiceDesc for UserAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.UserAuthService",
	HandlerType: (*UserAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _UserAuthService_GetUserInfo_Handler,
		},
		{
			MethodName: "UploadAvatar",
			Handler:    _UserAuthService_UploadAvatar_Handler,
		},
		{
			MethodName: "GetMFACode",
			Handler:    _UserAuthService_GetMFACode_Handler,
		},
		{
			MethodName: "BindMFA",
			Handler:    _UserAuthService_BindMFA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/users.proto",
}

const (
	SessionService_RefreshSession_FullMethodName = "/users.SessionService/RefreshSession"
	SessionService_Logout_FullMethodName         = "/users.SessionService/Logout"
)

// SessionServiceClient is the client API for SessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
//	message LogoutResponse{
//	 common.ErrorCode code = 1;
//	 string message = 2;
//	}
type SessionServiceClient interface {
	// 刷新会话
	RefreshSession(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
	// 登出
	Logout(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
}

type sessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionServiceClient(cc grpc.ClientConnInterface) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) RefreshSession(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, SessionService_RefreshSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) Logout(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, SessionService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServiceServer is the server API for SessionService service.
// All implementations must embed UnimplementedSessionServiceServer
// for forward compatibility.
//
//	message LogoutResponse{
//	 common.ErrorCode code = 1;
//	 string message = 2;
//	}
type SessionServiceServer interface {
	// 刷新会话
	RefreshSession(context.Context, *RefreshTokenRequest) (*common.CommonResponse, error)
	// 登出
	Logout(context.Context, *RefreshTokenRequest) (*common.CommonResponse, error)
	mustEmbedUnimplementedSessionServiceServer()
}

// UnimplementedSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionServiceServer struct{}

func (UnimplementedSessionServiceServer) RefreshSession(context.Context, *RefreshTokenRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshSession not implemented")
}
func (UnimplementedSessionServiceServer) Logout(context.Context, *RefreshTokenRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedSessionServiceServer) mustEmbedUnimplementedSessionServiceServer() {}
func (UnimplementedSessionServiceServer) testEmbeddedByValue()                        {}

// UnsafeSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionServiceServer will
// result in compilation errors.
type UnsafeSessionServiceServer interface {
	mustEmbedUnimplementedSessionServiceServer()
}

func RegisterSessionServiceServer(s grpc.ServiceRegistrar, srv SessionServiceServer) {
	// If the following call panics, it indicates UnimplementedSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionService_ServiceDesc, srv)
}

func _SessionService_RefreshSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).RefreshSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_RefreshSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).RefreshSession(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).Logout(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionService_ServiceDesc is the grpc.ServiceDesc for SessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RefreshSession",
			Handler:    _SessionService_RefreshSession_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _SessionService_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/users.proto",
}
