// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: idl/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_NOTHING             ErrorCode = 0
	ErrorCode_SUCCESS             ErrorCode = 1
	ErrorCode_REQUEST_ERROR       ErrorCode = 1000 // 获取请求失败
	ErrorCode_PARAM_ERROR         ErrorCode = 1001 // 参数错误
	ErrorCode_USER_NOT_LOGIN      ErrorCode = 2001 // 用户未登录
	ErrorCode_USER_EXIST          ErrorCode = 2002 // 用户已存在
	ErrorCode_USER_NOT_EXIST      ErrorCode = 2003 // 用户不存在
	ErrorCode_USER_PASSWORD_ERROR ErrorCode = 2004 // 用户密码错误
	ErrorCode_VIDEO_NOT_EXIST     ErrorCode = 3001 // 视频不存在
	ErrorCode_VIDEO_FORMAT_ERROR  ErrorCode = 3002 // 视频格式错误
	ErrorCode_COMMENT_NOT_EXIST   ErrorCode = 4001 // 评论不存在
	ErrorCode_OPERATION_FORBIDDEN ErrorCode = 5001 // 操作禁止（如删他人评论）
	ErrorCode_PROGRESS_ERROR      ErrorCode = 6001 // 其他错误
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:    "NOTHING",
		1:    "SUCCESS",
		1000: "REQUEST_ERROR",
		1001: "PARAM_ERROR",
		2001: "USER_NOT_LOGIN",
		2002: "USER_EXIST",
		2003: "USER_NOT_EXIST",
		2004: "USER_PASSWORD_ERROR",
		3001: "VIDEO_NOT_EXIST",
		3002: "VIDEO_FORMAT_ERROR",
		4001: "COMMENT_NOT_EXIST",
		5001: "OPERATION_FORBIDDEN",
		6001: "PROGRESS_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"NOTHING":             0,
		"SUCCESS":             1,
		"REQUEST_ERROR":       1000,
		"PARAM_ERROR":         1001,
		"USER_NOT_LOGIN":      2001,
		"USER_EXIST":          2002,
		"USER_NOT_EXIST":      2003,
		"USER_PASSWORD_ERROR": 2004,
		"VIDEO_NOT_EXIST":     3001,
		"VIDEO_FORMAT_ERROR":  3002,
		"COMMENT_NOT_EXIST":   4001,
		"OPERATION_FORBIDDEN": 5001,
		"PROGRESS_ERROR":      6001,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_idl_common_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_idl_common_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{0}
}

// 用户信息
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_idl_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_idl_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 视频信息
type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Views         int32                  `protobuf:"varint,5,opt,name=views,proto3" json:"views,omitempty"`
	Likes         int32                  `protobuf:"varint,6,opt,name=likes,proto3" json:"likes,omitempty"`
	Comments      int32                  `protobuf:"varint,7,opt,name=comments,proto3" json:"comments,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_idl_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_idl_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{1}
}

func (x *Video) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Video) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Video) GetViews() int32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *Video) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Video) GetComments() int32 {
	if x != nil {
		return x.Comments
	}
	return 0
}

func (x *Video) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Video) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 评论信息
type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Likes         int64                  `protobuf:"varint,6,opt,name=likes,proto3" json:"likes,omitempty"`
	UserInfo      *User                  `protobuf:"bytes,7,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	ReplyList     []*Comment             `protobuf:"bytes,8,rep,name=reply_list,json=replyList,proto3" json:"reply_list,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_idl_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_idl_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{2}
}

func (x *Comment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Comment) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *Comment) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Comment) GetUserInfo() *User {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *Comment) GetReplyList() []*Comment {
	if x != nil {
		return x.ReplyList
	}
	return nil
}

func (x *Comment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Comment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 点赞用户信息
type LikeUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserInfo      *User                  `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeUser) Reset() {
	*x = LikeUser{}
	mi := &file_idl_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeUser) ProtoMessage() {}

func (x *LikeUser) ProtoReflect() protoreflect.Message {
	mi := &file_idl_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeUser.ProtoReflect.Descriptor instead.
func (*LikeUser) Descriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{3}
}

func (x *LikeUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeUser) GetUserInfo() *User {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *LikeUser) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Token 信息
type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessExpire  string                 `protobuf:"bytes,1,opt,name=access_expire,json=accessExpire,proto3" json:"access_expire,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshExpire string                 `protobuf:"bytes,3,opt,name=refresh_expire,json=refreshExpire,proto3" json:"refresh_expire,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_idl_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_idl_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{4}
}

func (x *Token) GetAccessExpire() string {
	if x != nil {
		return x.AccessExpire
	}
	return ""
}

func (x *Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Token) GetRefreshExpire() string {
	if x != nil {
		return x.RefreshExpire
	}
	return ""
}

func (x *Token) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// MFA信息
type MFA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MfaSecret     string                 `protobuf:"bytes,1,opt,name=mfa_secret,json=mfaSecret,proto3" json:"mfa_secret,omitempty"`
	MfaQrcodeUrl  string                 `protobuf:"bytes,2,opt,name=mfa_qrcode_url,json=mfaQrcodeUrl,proto3" json:"mfa_qrcode_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MFA) Reset() {
	*x = MFA{}
	mi := &file_idl_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MFA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFA) ProtoMessage() {}

func (x *MFA) ProtoReflect() protoreflect.Message {
	mi := &file_idl_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFA.ProtoReflect.Descriptor instead.
func (*MFA) Descriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{5}
}

func (x *MFA) GetMfaSecret() string {
	if x != nil {
		return x.MfaSecret
	}
	return ""
}

func (x *MFA) GetMfaQrcodeUrl() string {
	if x != nil {
		return x.MfaQrcodeUrl
	}
	return ""
}

// 通用数据
type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *User                  `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	TokenInfo     *Token                 `protobuf:"bytes,2,opt,name=token_info,json=tokenInfo,proto3" json:"token_info,omitempty"`
	VideoList     []*Video               `protobuf:"bytes,3,rep,name=video_list,json=videoList,proto3" json:"video_list,omitempty"`
	VideoInfo     *Video                 `protobuf:"bytes,4,opt,name=video_info,json=videoInfo,proto3" json:"video_info,omitempty"`
	UserList      []*User                `protobuf:"bytes,5,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	CommentInfo   *Comment               `protobuf:"bytes,6,opt,name=comment_info,json=commentInfo,proto3" json:"comment_info,omitempty"`
	CommentList   []*Comment             `protobuf:"bytes,7,rep,name=comment_list,json=commentList,proto3" json:"comment_list,omitempty"`
	TotalCount    int32                  `protobuf:"varint,8,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	MfaInfo       *MFA                   `protobuf:"bytes,9,opt,name=mfa_info,json=mfaInfo,proto3" json:"mfa_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_idl_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_idl_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{6}
}

func (x *Data) GetUserInfo() *User {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *Data) GetTokenInfo() *Token {
	if x != nil {
		return x.TokenInfo
	}
	return nil
}

func (x *Data) GetVideoList() []*Video {
	if x != nil {
		return x.VideoList
	}
	return nil
}

func (x *Data) GetVideoInfo() *Video {
	if x != nil {
		return x.VideoInfo
	}
	return nil
}

func (x *Data) GetUserList() []*User {
	if x != nil {
		return x.UserList
	}
	return nil
}

func (x *Data) GetCommentInfo() *Comment {
	if x != nil {
		return x.CommentInfo
	}
	return nil
}

func (x *Data) GetCommentList() []*Comment {
	if x != nil {
		return x.CommentList
	}
	return nil
}

func (x *Data) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *Data) GetMfaInfo() *MFA {
	if x != nil {
		return x.MfaInfo
	}
	return nil
}

// 通用响应
type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=common.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Data                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_idl_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{7}
}

func (x *CommonResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_NOTHING
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommonResponse) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// 分页请求
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_idl_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_idl_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{8}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ID请求
type IDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDRequest) Reset() {
	*x = IDRequest{}
	mi := &file_idl_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequest) ProtoMessage() {}

func (x *IDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequest.ProtoReflect.Descriptor instead.
func (*IDRequest) Descriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{9}
}

func (x *IDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 文件上传请求
type FileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileKey       string                 `protobuf:"bytes,1,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`    // 文件键
	FileType      string                 `protobuf:"bytes,2,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"` // 文件类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	mi := &file_idl_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{10}
}

func (x *FileUploadRequest) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *FileUploadRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

var File_idl_common_proto protoreflect.FileDescriptor

const file_idl_common_proto_rawDesc = "" +
	"\n" +
	"\x10idl/common.proto\x12\x06common\"\xab\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\xf2\x01\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\x12\x14\n" +
	"\x05views\x18\x05 \x01(\x05R\x05views\x12\x14\n" +
	"\x05likes\x18\x06 \x01(\x05R\x05likes\x12\x1a\n" +
	"\bcomments\x18\a \x01(\x05R\bcomments\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xb3\x02\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\x03R\avideoId\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x03R\bparentId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x14\n" +
	"\x05likes\x18\x06 \x01(\x03R\x05likes\x12)\n" +
	"\tuser_info\x18\a \x01(\v2\f.common.UserR\buserInfo\x12.\n" +
	"\n" +
	"reply_list\x18\b \x03(\v2\x0f.common.CommentR\treplyList\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"m\n" +
	"\bLikeUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12)\n" +
	"\tuser_info\x18\x02 \x01(\v2\f.common.UserR\buserInfo\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"\x9b\x01\n" +
	"\x05Token\x12#\n" +
	"\raccess_expire\x18\x01 \x01(\tR\faccessExpire\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12%\n" +
	"\x0erefresh_expire\x18\x03 \x01(\tR\rrefreshExpire\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\"J\n" +
	"\x03MFA\x12\x1d\n" +
	"\n" +
	"mfa_secret\x18\x01 \x01(\tR\tmfaSecret\x12$\n" +
	"\x0emfa_qrcode_url\x18\x02 \x01(\tR\fmfaQrcodeUrl\"\x97\x03\n" +
	"\x04Data\x12)\n" +
	"\tuser_info\x18\x01 \x01(\v2\f.common.UserR\buserInfo\x12,\n" +
	"\n" +
	"token_info\x18\x02 \x01(\v2\r.common.TokenR\ttokenInfo\x12,\n" +
	"\n" +
	"video_list\x18\x03 \x03(\v2\r.common.VideoR\tvideoList\x12,\n" +
	"\n" +
	"video_info\x18\x04 \x01(\v2\r.common.VideoR\tvideoInfo\x12)\n" +
	"\tuser_list\x18\x05 \x03(\v2\f.common.UserR\buserList\x122\n" +
	"\fcomment_info\x18\x06 \x01(\v2\x0f.common.CommentR\vcommentInfo\x122\n" +
	"\fcomment_list\x18\a \x03(\v2\x0f.common.CommentR\vcommentList\x12\x1f\n" +
	"\vtotal_count\x18\b \x01(\x05R\n" +
	"totalCount\x12&\n" +
	"\bmfa_info\x18\t \x01(\v2\v.common.MFAR\amfaInfo\"s\n" +
	"\x0eCommonResponse\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.common.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\x04data\x18\x03 \x01(\v2\f.common.DataR\x04data\"=\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x1b\n" +
	"\tIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x11FileUploadRequest\x12\x19\n" +
	"\bfile_key\x18\x01 \x01(\tR\afileKey\x12\x1b\n" +
	"\tfile_type\x18\x02 \x01(\tR\bfileType*\x96\x02\n" +
	"\tErrorCode\x12\v\n" +
	"\aNOTHING\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\x12\n" +
	"\rREQUEST_ERROR\x10\xe8\a\x12\x10\n" +
	"\vPARAM_ERROR\x10\xe9\a\x12\x13\n" +
	"\x0eUSER_NOT_LOGIN\x10\xd1\x0f\x12\x0f\n" +
	"\n" +
	"USER_EXIST\x10\xd2\x0f\x12\x13\n" +
	"\x0eUSER_NOT_EXIST\x10\xd3\x0f\x12\x18\n" +
	"\x13USER_PASSWORD_ERROR\x10\xd4\x0f\x12\x14\n" +
	"\x0fVIDEO_NOT_EXIST\x10\xb9\x17\x12\x17\n" +
	"\x12VIDEO_FORMAT_ERROR\x10\xba\x17\x12\x16\n" +
	"\x11COMMENT_NOT_EXIST\x10\xa1\x1f\x12\x18\n" +
	"\x13OPERATION_FORBIDDEN\x10\x89'\x12\x13\n" +
	"\x0ePROGRESS_ERROR\x10\xf1.B\tZ\a/commonb\x06proto3"

var (
	file_idl_common_proto_rawDescOnce sync.Once
	file_idl_common_proto_rawDescData []byte
)

func file_idl_common_proto_rawDescGZIP() []byte {
	file_idl_common_proto_rawDescOnce.Do(func() {
		file_idl_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_common_proto_rawDesc), len(file_idl_common_proto_rawDesc)))
	})
	return file_idl_common_proto_rawDescData
}

var file_idl_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_idl_common_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_idl_common_proto_goTypes = []any{
	(ErrorCode)(0),            // 0: common.ErrorCode
	(*User)(nil),              // 1: common.User
	(*Video)(nil),             // 2: common.Video
	(*Comment)(nil),           // 3: common.Comment
	(*LikeUser)(nil),          // 4: common.LikeUser
	(*Token)(nil),             // 5: common.Token
	(*MFA)(nil),               // 6: common.MFA
	(*Data)(nil),              // 7: common.Data
	(*CommonResponse)(nil),    // 8: common.CommonResponse
	(*Pagination)(nil),        // 9: common.Pagination
	(*IDRequest)(nil),         // 10: common.IDRequest
	(*FileUploadRequest)(nil), // 11: common.FileUploadRequest
}
var file_idl_common_proto_depIdxs = []int32{
	1,  // 0: common.Comment.user_info:type_name -> common.User
	3,  // 1: common.Comment.reply_list:type_name -> common.Comment
	1,  // 2: common.LikeUser.user_info:type_name -> common.User
	1,  // 3: common.Data.user_info:type_name -> common.User
	5,  // 4: common.Data.token_info:type_name -> common.Token
	2,  // 5: common.Data.video_list:type_name -> common.Video
	2,  // 6: common.Data.video_info:type_name -> common.Video
	1,  // 7: common.Data.user_list:type_name -> common.User
	3,  // 8: common.Data.comment_info:type_name -> common.Comment
	3,  // 9: common.Data.comment_list:type_name -> common.Comment
	6,  // 10: common.Data.mfa_info:type_name -> common.MFA
	0,  // 11: common.CommonResponse.code:type_name -> common.ErrorCode
	7,  // 12: common.CommonResponse.data:type_name -> common.Data
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_idl_common_proto_init() }
func file_idl_common_proto_init() {
	if File_idl_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_common_proto_rawDesc), len(file_idl_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idl_common_proto_goTypes,
		DependencyIndexes: file_idl_common_proto_depIdxs,
		EnumInfos:         file_idl_common_proto_enumTypes,
		MessageInfos:      file_idl_common_proto_msgTypes,
	}.Build()
	File_idl_common_proto = out.File
	file_idl_common_proto_goTypes = nil
	file_idl_common_proto_depIdxs = nil
}
