// Code generated by hertz generator.

package users

import (
	"github.com/ZOEKOFK/video_web_v3/api_gateway/my_jwt"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{}
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{}
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{}
}

func _sessionsMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{}
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{}
}

func _refreshsessionMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{}
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{}
}

func _registerMw() []app.HandlerFunc {
	return []app.HandlerFunc{}
}

func _user_idMw() []app.HandlerFunc {
	return []app.HandlerFunc{}
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{my_jwt.AuthMiddleware.MiddlewareFunc()} //
}

func _uploadavatarMw() []app.HandlerFunc {
	return []app.HandlerFunc{my_jwt.AuthMiddleware.MiddlewareFunc()}
}

func _mfaMw() []app.HandlerFunc {
	return []app.HandlerFunc{my_jwt.AuthMiddleware.MiddlewareFunc()}
}

func _bindmfaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmfacodeMw() []app.HandlerFunc {
	// your code...
	return nil
}
