// Code generated by hertz generator.

package main

import (
	"log"

	"github.com/ZOEKOFK/video_web_v3/api_gateway/biz/router"
	"github.com/ZOEKOFK/video_web_v3/api_gateway/client"
	"github.com/ZOEKOFK/video_web_v3/api_gateway/my_jwt"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	//初始化JWT
	err := my_jwt.InitJWT()
	if err != nil {
		log.Println("init jwt fail")
	}
	// 初始化 gRPC 客户端
	client.InitGRPCClient()

	h := server.Default()

	router.GeneratedRegister(h)
	h.Spin()
}
