// Code generated by hertz generator.

package main

import (
	"log"

	"github.com/ZOEKOFK/video_web_v3/api_gateway/biz/router"
	"github.com/ZOEKOFK/video_web_v3/api_gateway/client"
	"github.com/ZOEKOFK/video_web_v3/api_gateway/my_jwt"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	err := my_jwt.InitJWT()
	if err != nil {
		log.Fatalf("init jwt fail: %v", err)
	}

	client.InitGRPCClient()

	h := server.Default(server.WithHostPorts(":8888"), server.WithMaxRequestBodySize(500*1024*1024))
	router.GeneratedRegister(h)
	h.Spin()
}
