// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: idl/social.proto

package social

import (
	common "github.com/ZOEKOFK/video_web_v3/app/pb/common"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FollowAuthService_FollowAction_FullMethodName  = "/social.FollowAuthService/FollowAction"
	FollowAuthService_GetFriendList_FullMethodName = "/social.FollowAuthService/GetFriendList"
)

// FollowAuthServiceClient is the client API for FollowAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 关注认证服务
type FollowAuthServiceClient interface {
	// 关注/取消关注
	// @router /api/follows [POST]
	FollowAction(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
	// 获取好友列表
	// @router /api/users/friends [GET]
	GetFriendList(ctx context.Context, in *FriendListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
}

type followAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFollowAuthServiceClient(cc grpc.ClientConnInterface) FollowAuthServiceClient {
	return &followAuthServiceClient{cc}
}

func (c *followAuthServiceClient) FollowAction(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, FollowAuthService_FollowAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followAuthServiceClient) GetFriendList(ctx context.Context, in *FriendListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, FollowAuthService_GetFriendList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FollowAuthServiceServer is the server API for FollowAuthService service.
// All implementations must embed UnimplementedFollowAuthServiceServer
// for forward compatibility.
//
// 关注认证服务
type FollowAuthServiceServer interface {
	// 关注/取消关注
	// @router /api/follows [POST]
	FollowAction(context.Context, *FollowRequest) (*common.CommonResponse, error)
	// 获取好友列表
	// @router /api/users/friends [GET]
	GetFriendList(context.Context, *FriendListRequest) (*common.CommonResponse, error)
	mustEmbedUnimplementedFollowAuthServiceServer()
}

// UnimplementedFollowAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFollowAuthServiceServer struct{}

func (UnimplementedFollowAuthServiceServer) FollowAction(context.Context, *FollowRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowAction not implemented")
}
func (UnimplementedFollowAuthServiceServer) GetFriendList(context.Context, *FriendListRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriendList not implemented")
}
func (UnimplementedFollowAuthServiceServer) mustEmbedUnimplementedFollowAuthServiceServer() {}
func (UnimplementedFollowAuthServiceServer) testEmbeddedByValue()                           {}

// UnsafeFollowAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FollowAuthServiceServer will
// result in compilation errors.
type UnsafeFollowAuthServiceServer interface {
	mustEmbedUnimplementedFollowAuthServiceServer()
}

func RegisterFollowAuthServiceServer(s grpc.ServiceRegistrar, srv FollowAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedFollowAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FollowAuthService_ServiceDesc, srv)
}

func _FollowAuthService_FollowAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowAuthServiceServer).FollowAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowAuthService_FollowAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowAuthServiceServer).FollowAction(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowAuthService_GetFriendList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowAuthServiceServer).GetFriendList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowAuthService_GetFriendList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowAuthServiceServer).GetFriendList(ctx, req.(*FriendListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FollowAuthService_ServiceDesc is the grpc.ServiceDesc for FollowAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FollowAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.FollowAuthService",
	HandlerType: (*FollowAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FollowAction",
			Handler:    _FollowAuthService_FollowAction_Handler,
		},
		{
			MethodName: "GetFriendList",
			Handler:    _FollowAuthService_GetFriendList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/social.proto",
}

const (
	FollowPublicService_GetFollowList_FullMethodName   = "/social.FollowPublicService/GetFollowList"
	FollowPublicService_GetFollowerList_FullMethodName = "/social.FollowPublicService/GetFollowerList"
)

// FollowPublicServiceClient is the client API for FollowPublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 关注公共服务
type FollowPublicServiceClient interface {
	// 获取关注列表
	// @router /api/users/:user_id/followings [GET]
	GetFollowList(ctx context.Context, in *FollowListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
	// 获取粉丝列表
	// @router /api/users/:user_id/followers [GET]
	GetFollowerList(ctx context.Context, in *FollowerListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
}

type followPublicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFollowPublicServiceClient(cc grpc.ClientConnInterface) FollowPublicServiceClient {
	return &followPublicServiceClient{cc}
}

func (c *followPublicServiceClient) GetFollowList(ctx context.Context, in *FollowListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, FollowPublicService_GetFollowList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followPublicServiceClient) GetFollowerList(ctx context.Context, in *FollowerListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, FollowPublicService_GetFollowerList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FollowPublicServiceServer is the server API for FollowPublicService service.
// All implementations must embed UnimplementedFollowPublicServiceServer
// for forward compatibility.
//
// 关注公共服务
type FollowPublicServiceServer interface {
	// 获取关注列表
	// @router /api/users/:user_id/followings [GET]
	GetFollowList(context.Context, *FollowListRequest) (*common.CommonResponse, error)
	// 获取粉丝列表
	// @router /api/users/:user_id/followers [GET]
	GetFollowerList(context.Context, *FollowerListRequest) (*common.CommonResponse, error)
	mustEmbedUnimplementedFollowPublicServiceServer()
}

// UnimplementedFollowPublicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFollowPublicServiceServer struct{}

func (UnimplementedFollowPublicServiceServer) GetFollowList(context.Context, *FollowListRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowList not implemented")
}
func (UnimplementedFollowPublicServiceServer) GetFollowerList(context.Context, *FollowerListRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowerList not implemented")
}
func (UnimplementedFollowPublicServiceServer) mustEmbedUnimplementedFollowPublicServiceServer() {}
func (UnimplementedFollowPublicServiceServer) testEmbeddedByValue()                             {}

// UnsafeFollowPublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FollowPublicServiceServer will
// result in compilation errors.
type UnsafeFollowPublicServiceServer interface {
	mustEmbedUnimplementedFollowPublicServiceServer()
}

func RegisterFollowPublicServiceServer(s grpc.ServiceRegistrar, srv FollowPublicServiceServer) {
	// If the following call panics, it indicates UnimplementedFollowPublicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FollowPublicService_ServiceDesc, srv)
}

func _FollowPublicService_GetFollowList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowPublicServiceServer).GetFollowList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowPublicService_GetFollowList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowPublicServiceServer).GetFollowList(ctx, req.(*FollowListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowPublicService_GetFollowerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowPublicServiceServer).GetFollowerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowPublicService_GetFollowerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowPublicServiceServer).GetFollowerList(ctx, req.(*FollowerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FollowPublicService_ServiceDesc is the grpc.ServiceDesc for FollowPublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FollowPublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.FollowPublicService",
	HandlerType: (*FollowPublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFollowList",
			Handler:    _FollowPublicService_GetFollowList_Handler,
		},
		{
			MethodName: "GetFollowerList",
			Handler:    _FollowPublicService_GetFollowerList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/social.proto",
}
