// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: idl/social.proto

package social

import (
	common "github.com/ZOEKOFK/video_web_v3/app/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 关注请求
type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`               // true关注 false取消关注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_idl_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_idl_social_proto_rawDescGZIP(), []int{0}
}

func (x *FollowRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// 关注列表请求
type FollowListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowListRequest) Reset() {
	*x = FollowListRequest{}
	mi := &file_idl_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListRequest) ProtoMessage() {}

func (x *FollowListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListRequest.ProtoReflect.Descriptor instead.
func (*FollowListRequest) Descriptor() ([]byte, []int) {
	return file_idl_social_proto_rawDescGZIP(), []int{1}
}

func (x *FollowListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FollowListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FollowListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 粉丝列表请求
type FollowerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowerListRequest) Reset() {
	*x = FollowerListRequest{}
	mi := &file_idl_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerListRequest) ProtoMessage() {}

func (x *FollowerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerListRequest.ProtoReflect.Descriptor instead.
func (*FollowerListRequest) Descriptor() ([]byte, []int) {
	return file_idl_social_proto_rawDescGZIP(), []int{2}
}

func (x *FollowerListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FollowerListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FollowerListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 好友列表请求
type FriendListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListRequest) Reset() {
	*x = FriendListRequest{}
	mi := &file_idl_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListRequest) ProtoMessage() {}

func (x *FriendListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListRequest.ProtoReflect.Descriptor instead.
func (*FriendListRequest) Descriptor() ([]byte, []int) {
	return file_idl_social_proto_rawDescGZIP(), []int{3}
}

func (x *FriendListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FriendListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FriendListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_idl_social_proto protoreflect.FileDescriptor

const file_idl_social_proto_rawDesc = "" +
	"\n" +
	"\x10idl/social.proto\x12\x06social\x1a\x10idl/common.proto\x1a\ridl/api.proto\"@\n" +
	"\rFollowRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\"]\n" +
	"\x11FollowListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"_\n" +
	"\x13FollowerListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"]\n" +
	"\x11FriendListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId2\xc0\x01\n" +
	"\x11FollowAuthService\x12O\n" +
	"\fFollowAction\x12\x15.social.FollowRequest\x1a\x16.common.CommonResponse\"\x10\xd2\xc1\x18\f/api/follows\x12Z\n" +
	"\rGetFriendList\x12\x19.social.FriendListRequest\x1a\x16.common.CommonResponse\"\x16\xca\xc1\x18\x12/api/users/friends2\xe8\x01\n" +
	"\x13FollowPublicService\x12f\n" +
	"\rGetFollowList\x12\x19.social.FollowListRequest\x1a\x16.common.CommonResponse\"\"\xca\xc1\x18\x1e/api/users/:user_id/followings\x12i\n" +
	"\x0fGetFollowerList\x12\x1b.social.FollowerListRequest\x1a\x16.common.CommonResponse\"!\xca\xc1\x18\x1d/api/users/:user_id/followersB\tZ\a/socialb\x06proto3"

var (
	file_idl_social_proto_rawDescOnce sync.Once
	file_idl_social_proto_rawDescData []byte
)

func file_idl_social_proto_rawDescGZIP() []byte {
	file_idl_social_proto_rawDescOnce.Do(func() {
		file_idl_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_social_proto_rawDesc), len(file_idl_social_proto_rawDesc)))
	})
	return file_idl_social_proto_rawDescData
}

var file_idl_social_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_idl_social_proto_goTypes = []any{
	(*FollowRequest)(nil),         // 0: social.FollowRequest
	(*FollowListRequest)(nil),     // 1: social.FollowListRequest
	(*FollowerListRequest)(nil),   // 2: social.FollowerListRequest
	(*FriendListRequest)(nil),     // 3: social.FriendListRequest
	(*common.CommonResponse)(nil), // 4: common.CommonResponse
}
var file_idl_social_proto_depIdxs = []int32{
	0, // 0: social.FollowAuthService.FollowAction:input_type -> social.FollowRequest
	3, // 1: social.FollowAuthService.GetFriendList:input_type -> social.FriendListRequest
	1, // 2: social.FollowPublicService.GetFollowList:input_type -> social.FollowListRequest
	2, // 3: social.FollowPublicService.GetFollowerList:input_type -> social.FollowerListRequest
	4, // 4: social.FollowAuthService.FollowAction:output_type -> common.CommonResponse
	4, // 5: social.FollowAuthService.GetFriendList:output_type -> common.CommonResponse
	4, // 6: social.FollowPublicService.GetFollowList:output_type -> common.CommonResponse
	4, // 7: social.FollowPublicService.GetFollowerList:output_type -> common.CommonResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_social_proto_init() }
func file_idl_social_proto_init() {
	if File_idl_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_social_proto_rawDesc), len(file_idl_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_idl_social_proto_goTypes,
		DependencyIndexes: file_idl_social_proto_depIdxs,
		MessageInfos:      file_idl_social_proto_msgTypes,
	}.Build()
	File_idl_social_proto = out.File
	file_idl_social_proto_goTypes = nil
	file_idl_social_proto_depIdxs = nil
}
