// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: idl/videos.proto

package videos

import (
	common "github.com/ZOEKOFK/video_web_v3/app/pb/common"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoPublicService_SearchVideos_FullMethodName  = "/videos.VideoPublicService/SearchVideos"
	VideoPublicService_GetHotVideos_FullMethodName  = "/videos.VideoPublicService/GetHotVideos"
	VideoPublicService_GetUserVideos_FullMethodName = "/videos.VideoPublicService/GetUserVideos"
)

// VideoPublicServiceClient is the client API for VideoPublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 视频公共服务
type VideoPublicServiceClient interface {
	SearchVideos(ctx context.Context, in *SearchVideoRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
	GetHotVideos(ctx context.Context, in *HotVideoRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
	GetUserVideos(ctx context.Context, in *UserVideoListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
}

type videoPublicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoPublicServiceClient(cc grpc.ClientConnInterface) VideoPublicServiceClient {
	return &videoPublicServiceClient{cc}
}

func (c *videoPublicServiceClient) SearchVideos(ctx context.Context, in *SearchVideoRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, VideoPublicService_SearchVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoPublicServiceClient) GetHotVideos(ctx context.Context, in *HotVideoRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, VideoPublicService_GetHotVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoPublicServiceClient) GetUserVideos(ctx context.Context, in *UserVideoListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, VideoPublicService_GetUserVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoPublicServiceServer is the server API for VideoPublicService service.
// All implementations must embed UnimplementedVideoPublicServiceServer
// for forward compatibility.
//
// 视频公共服务
type VideoPublicServiceServer interface {
	SearchVideos(context.Context, *SearchVideoRequest) (*common.CommonResponse, error)
	GetHotVideos(context.Context, *HotVideoRequest) (*common.CommonResponse, error)
	GetUserVideos(context.Context, *UserVideoListRequest) (*common.CommonResponse, error)
	mustEmbedUnimplementedVideoPublicServiceServer()
}

// UnimplementedVideoPublicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoPublicServiceServer struct{}

func (UnimplementedVideoPublicServiceServer) SearchVideos(context.Context, *SearchVideoRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchVideos not implemented")
}
func (UnimplementedVideoPublicServiceServer) GetHotVideos(context.Context, *HotVideoRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHotVideos not implemented")
}
func (UnimplementedVideoPublicServiceServer) GetUserVideos(context.Context, *UserVideoListRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserVideos not implemented")
}
func (UnimplementedVideoPublicServiceServer) mustEmbedUnimplementedVideoPublicServiceServer() {}
func (UnimplementedVideoPublicServiceServer) testEmbeddedByValue()                            {}

// UnsafeVideoPublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoPublicServiceServer will
// result in compilation errors.
type UnsafeVideoPublicServiceServer interface {
	mustEmbedUnimplementedVideoPublicServiceServer()
}

func RegisterVideoPublicServiceServer(s grpc.ServiceRegistrar, srv VideoPublicServiceServer) {
	// If the following call panics, it indicates UnimplementedVideoPublicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoPublicService_ServiceDesc, srv)
}

func _VideoPublicService_SearchVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoPublicServiceServer).SearchVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoPublicService_SearchVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoPublicServiceServer).SearchVideos(ctx, req.(*SearchVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoPublicService_GetHotVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoPublicServiceServer).GetHotVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoPublicService_GetHotVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoPublicServiceServer).GetHotVideos(ctx, req.(*HotVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoPublicService_GetUserVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserVideoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoPublicServiceServer).GetUserVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoPublicService_GetUserVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoPublicServiceServer).GetUserVideos(ctx, req.(*UserVideoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoPublicService_ServiceDesc is the grpc.ServiceDesc for VideoPublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoPublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "videos.VideoPublicService",
	HandlerType: (*VideoPublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchVideos",
			Handler:    _VideoPublicService_SearchVideos_Handler,
		},
		{
			MethodName: "GetHotVideos",
			Handler:    _VideoPublicService_GetHotVideos_Handler,
		},
		{
			MethodName: "GetUserVideos",
			Handler:    _VideoPublicService_GetUserVideos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/videos.proto",
}

const (
	VideoAuthService_UploadVideo_FullMethodName = "/videos.VideoAuthService/UploadVideo"
)

// VideoAuthServiceClient is the client API for VideoAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 视频认证服务
type VideoAuthServiceClient interface {
	UploadVideo(ctx context.Context, in *UploadVideoRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
}

type videoAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoAuthServiceClient(cc grpc.ClientConnInterface) VideoAuthServiceClient {
	return &videoAuthServiceClient{cc}
}

func (c *videoAuthServiceClient) UploadVideo(ctx context.Context, in *UploadVideoRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, VideoAuthService_UploadVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoAuthServiceServer is the server API for VideoAuthService service.
// All implementations must embed UnimplementedVideoAuthServiceServer
// for forward compatibility.
//
// 视频认证服务
type VideoAuthServiceServer interface {
	UploadVideo(context.Context, *UploadVideoRequest) (*common.CommonResponse, error)
	mustEmbedUnimplementedVideoAuthServiceServer()
}

// UnimplementedVideoAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoAuthServiceServer struct{}

func (UnimplementedVideoAuthServiceServer) UploadVideo(context.Context, *UploadVideoRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadVideo not implemented")
}
func (UnimplementedVideoAuthServiceServer) mustEmbedUnimplementedVideoAuthServiceServer() {}
func (UnimplementedVideoAuthServiceServer) testEmbeddedByValue()                          {}

// UnsafeVideoAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoAuthServiceServer will
// result in compilation errors.
type UnsafeVideoAuthServiceServer interface {
	mustEmbedUnimplementedVideoAuthServiceServer()
}

func RegisterVideoAuthServiceServer(s grpc.ServiceRegistrar, srv VideoAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedVideoAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoAuthService_ServiceDesc, srv)
}

func _VideoAuthService_UploadVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoAuthServiceServer).UploadVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoAuthService_UploadVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoAuthServiceServer).UploadVideo(ctx, req.(*UploadVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoAuthService_ServiceDesc is the grpc.ServiceDesc for VideoAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "videos.VideoAuthService",
	HandlerType: (*VideoAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadVideo",
			Handler:    _VideoAuthService_UploadVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/videos.proto",
}
