// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: idl/videos.proto

package videos

import (
	common "github.com/ZOEKOFK/video_web_v3/app/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 上传视频请求
type UploadVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                                      // 标题
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                          // 描述
	File          []byte                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`                                        // 视频文件数据
	FileExtension string                 `protobuf:"bytes,4,opt,name=file_extension,json=fileExtension,proto3" json:"file_extension,omitempty"` // 文件后缀，如 "mp4", "avi", "mov"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoRequest) Reset() {
	*x = UploadVideoRequest{}
	mi := &file_idl_videos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoRequest) ProtoMessage() {}

func (x *UploadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_videos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadVideoRequest) Descriptor() ([]byte, []int) {
	return file_idl_videos_proto_rawDescGZIP(), []int{0}
}

func (x *UploadVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadVideoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UploadVideoRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *UploadVideoRequest) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

// 用户视频列表请求
type UserVideoListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	Id            uint64                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserVideoListRequest) Reset() {
	*x = UserVideoListRequest{}
	mi := &file_idl_videos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserVideoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserVideoListRequest) ProtoMessage() {}

func (x *UserVideoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_videos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserVideoListRequest.ProtoReflect.Descriptor instead.
func (*UserVideoListRequest) Descriptor() ([]byte, []int) {
	return file_idl_videos_proto_rawDescGZIP(), []int{1}
}

func (x *UserVideoListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserVideoListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *UserVideoListRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 搜索视频请求
type SearchVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`                    // 关键词
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`                          // 排序方式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideoRequest) Reset() {
	*x = SearchVideoRequest{}
	mi := &file_idl_videos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideoRequest) ProtoMessage() {}

func (x *SearchVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_videos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideoRequest.ProtoReflect.Descriptor instead.
func (*SearchVideoRequest) Descriptor() ([]byte, []int) {
	return file_idl_videos_proto_rawDescGZIP(), []int{2}
}

func (x *SearchVideoRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchVideoRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchVideoRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchVideoRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

// 热门视频请求
type HotVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // 数量限制
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`    // 类型
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`   // 页码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotVideoRequest) Reset() {
	*x = HotVideoRequest{}
	mi := &file_idl_videos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotVideoRequest) ProtoMessage() {}

func (x *HotVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_videos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotVideoRequest.ProtoReflect.Descriptor instead.
func (*HotVideoRequest) Descriptor() ([]byte, []int) {
	return file_idl_videos_proto_rawDescGZIP(), []int{3}
}

func (x *HotVideoRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *HotVideoRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HotVideoRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

var File_idl_videos_proto protoreflect.FileDescriptor

const file_idl_videos_proto_rawDesc = "" +
	"\n" +
	"\x10idl/videos.proto\x12\x06videos\x1a\x10idl/common.proto\x1a\ridl/api.proto\"\x87\x01\n" +
	"\x12UploadVideoRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04file\x18\x03 \x01(\fR\x04file\x12%\n" +
	"\x0efile_extension\x18\x04 \x01(\tR\rfileExtension\"W\n" +
	"\x14UserVideoListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x04R\x02id\"s\n" +
	"\x12SearchVideoRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\"O\n" +
	"\x0fHotVideoRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page2\xad\x02\n" +
	"\x12VideoPublicService\x12Z\n" +
	"\fSearchVideos\x12\x1a.videos.SearchVideoRequest\x1a\x16.common.CommonResponse\"\x16\xca\xc1\x18\x12/api/videos/search\x12T\n" +
	"\fGetHotVideos\x12\x17.videos.HotVideoRequest\x1a\x16.common.CommonResponse\"\x13\xca\xc1\x18\x0f/api/videos/hot\x12e\n" +
	"\rGetUserVideos\x12\x1c.videos.UserVideoListRequest\x1a\x16.common.CommonResponse\"\x1e\xca\xc1\x18\x1a/api/users/:user_id/videos2f\n" +
	"\x10VideoAuthService\x12R\n" +
	"\vUploadVideo\x12\x1a.videos.UploadVideoRequest\x1a\x16.common.CommonResponse\"\x0f\xd2\xc1\x18\v/api/videosB\tZ\a/videosb\x06proto3"

var (
	file_idl_videos_proto_rawDescOnce sync.Once
	file_idl_videos_proto_rawDescData []byte
)

func file_idl_videos_proto_rawDescGZIP() []byte {
	file_idl_videos_proto_rawDescOnce.Do(func() {
		file_idl_videos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_videos_proto_rawDesc), len(file_idl_videos_proto_rawDesc)))
	})
	return file_idl_videos_proto_rawDescData
}

var file_idl_videos_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_idl_videos_proto_goTypes = []any{
	(*UploadVideoRequest)(nil),    // 0: videos.UploadVideoRequest
	(*UserVideoListRequest)(nil),  // 1: videos.UserVideoListRequest
	(*SearchVideoRequest)(nil),    // 2: videos.SearchVideoRequest
	(*HotVideoRequest)(nil),       // 3: videos.HotVideoRequest
	(*common.CommonResponse)(nil), // 4: common.CommonResponse
}
var file_idl_videos_proto_depIdxs = []int32{
	2, // 0: videos.VideoPublicService.SearchVideos:input_type -> videos.SearchVideoRequest
	3, // 1: videos.VideoPublicService.GetHotVideos:input_type -> videos.HotVideoRequest
	1, // 2: videos.VideoPublicService.GetUserVideos:input_type -> videos.UserVideoListRequest
	0, // 3: videos.VideoAuthService.UploadVideo:input_type -> videos.UploadVideoRequest
	4, // 4: videos.VideoPublicService.SearchVideos:output_type -> common.CommonResponse
	4, // 5: videos.VideoPublicService.GetHotVideos:output_type -> common.CommonResponse
	4, // 6: videos.VideoPublicService.GetUserVideos:output_type -> common.CommonResponse
	4, // 7: videos.VideoAuthService.UploadVideo:output_type -> common.CommonResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_videos_proto_init() }
func file_idl_videos_proto_init() {
	if File_idl_videos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_videos_proto_rawDesc), len(file_idl_videos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_idl_videos_proto_goTypes,
		DependencyIndexes: file_idl_videos_proto_depIdxs,
		MessageInfos:      file_idl_videos_proto_msgTypes,
	}.Build()
	File_idl_videos_proto = out.File
	file_idl_videos_proto_goTypes = nil
	file_idl_videos_proto_depIdxs = nil
}
