// Code generated by hertz generator.

package videos

import (
	"context"
	"log"
	"net/http"
	"strconv"

	"github.com/ZOEKOFK/video_web_v3/api_gateway/client"
	common "github.com/ZOEKOFK/video_web_v3/app/pb/common"
	videos "github.com/ZOEKOFK/video_web_v3/app/pb/videos"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// SearchVideos .
// @router /api/videos/search [GET]
func SearchVideos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req videos.SearchVideoRequest
	err = c.Bind(&req)
	log.Println(req.Page)
	if err != nil {
		c.JSON(consts.StatusBadRequest, client.FailResponse("SearchVideo", common.ErrorCode_REQUEST_ERROR))
		return
	}

	resp, err := client.VideoPublicServiceClient.SearchVideos(ctx, &req)
	if err != nil {
		c.JSON(http.StatusInternalServerError, resp)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// GetHotVideos .
// @router /api/videos/hot [GET]
func GetHotVideos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req videos.HotVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, client.FailResponse("GetHotVideo", common.ErrorCode_REQUEST_ERROR))
		return
	}

	resp, err := client.VideoPublicServiceClient.GetHotVideos(ctx, &req)
	if err != nil {
		c.JSON(http.StatusInternalServerError, resp)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// GetUserVideos .
// @router /api/users/:user_id/videos [GET]
func GetUserVideos(ctx context.Context, c *app.RequestContext) {
	id := c.Param("user_id")
	var err error
	var req videos.UserVideoListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	req.Id, _ = strconv.ParseUint(id, 10, 64)
	resp, err := client.VideoPublicServiceClient.GetUserVideos(ctx, &req)
	c.JSON(consts.StatusOK, resp)
}
