// Code generated by hertz generator.

package videos

import (
	"bytes"
	"context"
	"io"
	"log"
	"path/filepath"

	"github.com/ZOEKOFK/video_web_v3/api_gateway/client"
	"github.com/ZOEKOFK/video_web_v3/api_gateway/my_jwt"
	commonpb "github.com/ZOEKOFK/video_web_v3/app/pb/common"
	videospb "github.com/ZOEKOFK/video_web_v3/app/pb/videos"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// UploadVideo .
// @router /api/videos [POST]
func UploadVideo(ctx context.Context, c *app.RequestContext) {
	userID, err := my_jwt.GetUserIDFromToken(ctx, c)
	if err != nil {
		log.Printf("token 提取用户 ID 失败: %v", err)
		c.JSON(consts.StatusUnauthorized, client.FailResponse("invalid token", commonpb.ErrorCode_USER_NOT_LOGIN))
		return
	}

	fileHeader, err := c.FormFile("video")
	if err != nil {
		log.Printf("获取文件失败: %v", err)
		c.JSON(consts.StatusBadRequest, client.FailResponse("video file is required", commonpb.ErrorCode_PARAM_ERROR))
		return
	}
	file, err := fileHeader.Open()
	if err != nil {
		log.Printf("打开文件失败: %v", err)
		c.JSON(consts.StatusBadRequest, client.FailResponse("failed to open file", commonpb.ErrorCode_PARAM_ERROR))
		return
	}
	defer file.Close()

	var buf bytes.Buffer
	if _, err = io.Copy(&buf, file); err != nil {
		log.Printf("读取文件失败: %v", err)
		c.JSON(consts.StatusBadRequest, client.FailResponse("failed to read file", commonpb.ErrorCode_PARAM_ERROR))
		return
	}

	title := string(c.FormValue("title"))
	description := string(c.FormValue("description"))
	fileExt := filepath.Ext(fileHeader.Filename)

	log.Printf("[UploadVideo] user_id=%d, title=%s, file=%s, ext=%s", userID, title, fileHeader.Filename, fileExt)

	ctxWithUserID := client.WithUserID(ctx, userID)

	req := &videospb.UploadVideoRequest{
		Title:         title,
		Description:   description,
		File:          buf.Bytes(),
		FileExtension: fileExt,
	}

	grpcResp, err := client.VideoAuthServiceClient.UploadVideo(ctxWithUserID, req)
	if err != nil {
		log.Printf("[UploadVideo] gRPC 调用失败: %v", err)
		c.JSON(consts.StatusInternalServerError, client.FailResponse(err.Error(), commonpb.ErrorCode_PROGRESS_ERROR))
		return
	}

	c.JSON(consts.StatusOK, grpcResp)
}
