// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	users "github.com/ZOEKOFK/video_web_v3/api_gateway/biz/router/users"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	users.Register(r)
}
