// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	interaction "github.com/ZOEKOFK/video_web_v3/api_gateway/biz/router/interaction"
	social "github.com/ZOEKOFK/video_web_v3/api_gateway/biz/router/social"
	users "github.com/ZOEKOFK/video_web_v3/api_gateway/biz/router/users"
	videos "github.com/ZOEKOFK/video_web_v3/api_gateway/biz/router/videos"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	interaction.Register(r)

	social.Register(r)

	videos.Register(r)

	users.Register(r)
}
