// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: idl/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_SUCCESS             ErrorCode = 0    // 成功
	ErrorCode_REQUEST_ERROR       ErrorCode = 1    // 获取请求失败
	ErrorCode_PARAM_ERROR         ErrorCode = 1001 // 参数错误
	ErrorCode_USER_NOT_LOGIN      ErrorCode = 2001 // 用户未登录
	ErrorCode_USER_EXIST          ErrorCode = 2002 // 用户已存在
	ErrorCode_USER_NOT_EXIST      ErrorCode = 2003 // 用户不存在
	ErrorCode_USER_PASSWORD_ERROR ErrorCode = 2004 // 用户密码错误
	ErrorCode_VIDEO_NOT_EXIST     ErrorCode = 3001 // 视频不存在
	ErrorCode_VIDEO_FORMAT_ERROR  ErrorCode = 3002 // 视频格式错误
	ErrorCode_COMMENT_NOT_EXIST   ErrorCode = 4001 // 评论不存在
	ErrorCode_OPERATION_FORBIDDEN ErrorCode = 5001 // 操作禁止（如删他人评论）
	ErrorCode_PROGRESS_ERROR      ErrorCode = 6001 // 其他错误
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:    "SUCCESS",
		1:    "REQUEST_ERROR",
		1001: "PARAM_ERROR",
		2001: "USER_NOT_LOGIN",
		2002: "USER_EXIST",
		2003: "USER_NOT_EXIST",
		2004: "USER_PASSWORD_ERROR",
		3001: "VIDEO_NOT_EXIST",
		3002: "VIDEO_FORMAT_ERROR",
		4001: "COMMENT_NOT_EXIST",
		5001: "OPERATION_FORBIDDEN",
		6001: "PROGRESS_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"SUCCESS":             0,
		"REQUEST_ERROR":       1,
		"PARAM_ERROR":         1001,
		"USER_NOT_LOGIN":      2001,
		"USER_EXIST":          2002,
		"USER_NOT_EXIST":      2003,
		"USER_PASSWORD_ERROR": 2004,
		"VIDEO_NOT_EXIST":     3001,
		"VIDEO_FORMAT_ERROR":  3002,
		"COMMENT_NOT_EXIST":   4001,
		"OPERATION_FORBIDDEN": 5001,
		"PROGRESS_ERROR":      6001,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_idl_common_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_idl_common_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{0}
}

// 通用响应结构
type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=common.ErrorCode" json:"code,omitempty"` // 错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                  // 消息
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                        // 数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_idl_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_SUCCESS
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommonResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 分页请求
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_idl_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_idl_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ID请求
type IDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDRequest) Reset() {
	*x = IDRequest{}
	mi := &file_idl_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequest) ProtoMessage() {}

func (x *IDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequest.ProtoReflect.Descriptor instead.
func (*IDRequest) Descriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{2}
}

func (x *IDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 文件上传请求
type FileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileKey       string                 `protobuf:"bytes,1,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`    // 文件键
	FileType      string                 `protobuf:"bytes,2,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"` // 文件类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	mi := &file_idl_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_idl_common_proto_rawDescGZIP(), []int{3}
}

func (x *FileUploadRequest) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *FileUploadRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

var File_idl_common_proto protoreflect.FileDescriptor

const file_idl_common_proto_rawDesc = "" +
	"\n" +
	"\x10idl/common.proto\x12\x06common\"e\n" +
	"\x0eCommonResponse\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.common.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"=\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x1b\n" +
	"\tIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x11FileUploadRequest\x12\x19\n" +
	"\bfile_key\x18\x01 \x01(\tR\afileKey\x12\x1b\n" +
	"\tfile_type\x18\x02 \x01(\tR\bfileType*\x88\x02\n" +
	"\tErrorCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x11\n" +
	"\rREQUEST_ERROR\x10\x01\x12\x10\n" +
	"\vPARAM_ERROR\x10\xe9\a\x12\x13\n" +
	"\x0eUSER_NOT_LOGIN\x10\xd1\x0f\x12\x0f\n" +
	"\n" +
	"USER_EXIST\x10\xd2\x0f\x12\x13\n" +
	"\x0eUSER_NOT_EXIST\x10\xd3\x0f\x12\x18\n" +
	"\x13USER_PASSWORD_ERROR\x10\xd4\x0f\x12\x14\n" +
	"\x0fVIDEO_NOT_EXIST\x10\xb9\x17\x12\x17\n" +
	"\x12VIDEO_FORMAT_ERROR\x10\xba\x17\x12\x16\n" +
	"\x11COMMENT_NOT_EXIST\x10\xa1\x1f\x12\x18\n" +
	"\x13OPERATION_FORBIDDEN\x10\x89'\x12\x13\n" +
	"\x0ePROGRESS_ERROR\x10\xf1.B\tZ\a/commonb\x06proto3"

var (
	file_idl_common_proto_rawDescOnce sync.Once
	file_idl_common_proto_rawDescData []byte
)

func file_idl_common_proto_rawDescGZIP() []byte {
	file_idl_common_proto_rawDescOnce.Do(func() {
		file_idl_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_common_proto_rawDesc), len(file_idl_common_proto_rawDesc)))
	})
	return file_idl_common_proto_rawDescData
}

var file_idl_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_idl_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_idl_common_proto_goTypes = []any{
	(ErrorCode)(0),            // 0: common.ErrorCode
	(*CommonResponse)(nil),    // 1: common.CommonResponse
	(*Pagination)(nil),        // 2: common.Pagination
	(*IDRequest)(nil),         // 3: common.IDRequest
	(*FileUploadRequest)(nil), // 4: common.FileUploadRequest
}
var file_idl_common_proto_depIdxs = []int32{
	0, // 0: common.CommonResponse.code:type_name -> common.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_idl_common_proto_init() }
func file_idl_common_proto_init() {
	if File_idl_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_common_proto_rawDesc), len(file_idl_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idl_common_proto_goTypes,
		DependencyIndexes: file_idl_common_proto_depIdxs,
		EnumInfos:         file_idl_common_proto_enumTypes,
		MessageInfos:      file_idl_common_proto_msgTypes,
	}.Build()
	File_idl_common_proto = out.File
	file_idl_common_proto_goTypes = nil
	file_idl_common_proto_depIdxs = nil
}
