// Code generated by hertz generator.

package users

import (
	"context"
	"log"
	"net/http"

	"github.com/ZOEKOFK/video_web_v3/api_gateway/client"
	"github.com/ZOEKOFK/video_web_v3/app/pb/common"
	userspb "github.com/ZOEKOFK/video_web_v3/app/pb/users"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Register .
// @router /api/users [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userspb.UserRegisterRequest
	err = c.BindJSON(&req)
	log.Println(req.Password)
	if err != nil {
		c.JSON(http.StatusBadRequest, client.FailResponse("Register", common.ErrorCode_REQUEST_ERROR))
		return
	}
	grpcResp, err := client.UserPublicServiceClient.Register(ctx, &req)
	if err != nil {
		c.JSON(http.StatusInternalServerError, grpcResp)
		return
	}
	c.JSON(consts.StatusOK, grpcResp)
}

// Login .
// @router /api/sessions [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var req userspb.UserLoginRequest
	if err := c.Bind(&req); err != nil {
		c.JSON(http.StatusBadRequest, client.FailResponse("Invalid request", common.ErrorCode_PARAM_ERROR))
		return
	}
	log.Println(req.Password)
	resp, err := client.UserPublicServiceClient.Login(ctx, &req)
	if err != nil {
		c.JSON(http.StatusInternalServerError, resp)
		return
	}
	c.JSON(consts.StatusOK, resp)
}
