// Code generated by hertz generator.

package users

import (
	"context"
	"log"

	"github.com/ZOEKOFK/video_web_v3/api_gateway/client"
	"github.com/ZOEKOFK/video_web_v3/api_gateway/my_jwt"
	commonpb "github.com/ZOEKOFK/video_web_v3/app/pb/common"
	userspb "github.com/ZOEKOFK/video_web_v3/app/pb/users"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetUserInfo .
// @router /api/users/:user_id [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	
	// ============================================
	// 完整的 Access Token → Metadata → gRPC 流程
	// ============================================
	
	// 1️⃣ 从 Access Token 中提取用户 ID
	userID, err := my_jwt.GetUserIDFromToken(ctx, c)
	if err != nil {
		log.Printf("[GetUserInfo] 从 Token 提取用户 ID 失败: %v", err)
		c.JSON(consts.StatusUnauthorized, client.FailResponse("invalid token", commonpb.ErrorCode_USER_NOT_LOGIN))
		return
	}
	log.Printf("[GetUserInfo] 从 Token 中提取到用户 ID: %d", userID)
	
	// 2️⃣ 将用户 ID 添加到 gRPC Metadata 中
	ctxWithUserID := client.WithUserID(ctx, userID)
	log.Printf("[GetUserInfo] 用户 ID 已添加到 Metadata")
	
	// 3️⃣ 调用 gRPC 微服务（gRPC 服务端可以从 Metadata 中提取用户 ID）
	var req commonpb.IDRequest
	req.Id = c.Param("user_id")
	
	grpcResp, err := client.UserAuthServiceClient.GetUserInfo(ctxWithUserID, &req)
	if err != nil {
		log.Printf("[GetUserInfo] gRPC 调用失败: %v", err)
		c.JSON(consts.StatusInternalServerError, client.FailResponse(err.Error(), commonpb.ErrorCode_PROGRESS_ERROR))
		return
	}
	c.JSON(consts.StatusOK, grpcResp)
}

// UploadAvatar .
// @router /api/users/:user_id/avatar [POST]
func UploadAvatar(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userspb.UploadAvatarRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用 gRPC 微服务上传头像
	grpcResp, err := client.UserAuthServiceClient.UploadAvatar(ctx, &req)
	if err != nil {
		log.Printf("UploadAvatar grpc error: %v", err)
		c.JSON(consts.StatusInternalServerError, grpcResp)
		return
	}

	c.JSON(consts.StatusOK, grpcResp)
}