// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: idl/interaction.proto

package interaction

import (
	common "github.com/ZOEKOFK/video_web_v3/app/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 点赞操作请求
type LikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      int64                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 目标ID（视频/评论ID）
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`                         // 类型：1视频 2评论
	Status        bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                     // 点赞状态：true点赞 false取消点赞
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	mi := &file_idl_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_idl_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *LikeRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *LikeRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *LikeRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// 点赞列表请求
type LikeListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      int64                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 目标ID
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`                         // 类型：1视频 2评论
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeListRequest) Reset() {
	*x = LikeListRequest{}
	mi := &file_idl_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeListRequest) ProtoMessage() {}

func (x *LikeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeListRequest.ProtoReflect.Descriptor instead.
func (*LikeListRequest) Descriptor() ([]byte, []int) {
	return file_idl_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *LikeListRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *LikeListRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *LikeListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *LikeListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 发表评论请求
type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`    // 视频ID
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 父评论ID（0表示一级评论）
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                    // 评论内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_idl_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_idl_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommentRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *CreateCommentRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 评论列表请求
type CommentListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`    // 视频ID
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentListRequest) Reset() {
	*x = CommentListRequest{}
	mi := &file_idl_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListRequest) ProtoMessage() {}

func (x *CommentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListRequest.ProtoReflect.Descriptor instead.
func (*CommentListRequest) Descriptor() ([]byte, []int) {
	return file_idl_interaction_proto_rawDescGZIP(), []int{3}
}

func (x *CommentListRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *CommentListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CommentListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 删除评论请求
type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"` // 评论ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_idl_interaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_interaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_idl_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCommentRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

var File_idl_interaction_proto protoreflect.FileDescriptor

const file_idl_interaction_proto_rawDesc = "" +
	"\n" +
	"\x15idl/interaction.proto\x12\vinteraction\x1a\x10idl/common.proto\x1a\ridl/api.proto\"V\n" +
	"\vLikeRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x03R\btargetId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\"s\n" +
	"\x0fLikeListRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x03R\btargetId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"h\n" +
	"\x14CreateCommentRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"`\n" +
	"\x12CommentListRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"5\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId2\xbb\x01\n" +
	"\x0fLikeAuthService\x12N\n" +
	"\n" +
	"LikeAction\x12\x18.interaction.LikeRequest\x1a\x16.common.CommonResponse\"\x0e\xd2\xc1\x18\n" +
	"/api/likes\x12X\n" +
	"\vGetLikeList\x12\x1c.interaction.LikeListRequest\x1a\x16.common.CommonResponse\"\x13\xca\xc1\x18\x0f/api/likes/list2\xde\x01\n" +
	"\x12CommentAuthService\x12]\n" +
	"\rCreateComment\x12!.interaction.CreateCommentRequest\x1a\x16.common.CommonResponse\"\x11\xd2\xc1\x18\r/api/comments\x12i\n" +
	"\rDeleteComment\x12!.interaction.DeleteCommentRequest\x1a\x16.common.CommonResponse\"\x1d\xe2\xc1\x18\x19/api/comments/:comment_id2\x85\x01\n" +
	"\x14CommentPublicService\x12m\n" +
	"\x0eGetCommentList\x12\x1f.interaction.CommentListRequest\x1a\x16.common.CommonResponse\"\"\xca\xc1\x18\x1e/api/videos/:video_id/commentsB\x0eZ\f/interactionb\x06proto3"

var (
	file_idl_interaction_proto_rawDescOnce sync.Once
	file_idl_interaction_proto_rawDescData []byte
)

func file_idl_interaction_proto_rawDescGZIP() []byte {
	file_idl_interaction_proto_rawDescOnce.Do(func() {
		file_idl_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_interaction_proto_rawDesc), len(file_idl_interaction_proto_rawDesc)))
	})
	return file_idl_interaction_proto_rawDescData
}

var file_idl_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_idl_interaction_proto_goTypes = []any{
	(*LikeRequest)(nil),           // 0: interaction.LikeRequest
	(*LikeListRequest)(nil),       // 1: interaction.LikeListRequest
	(*CreateCommentRequest)(nil),  // 2: interaction.CreateCommentRequest
	(*CommentListRequest)(nil),    // 3: interaction.CommentListRequest
	(*DeleteCommentRequest)(nil),  // 4: interaction.DeleteCommentRequest
	(*common.CommonResponse)(nil), // 5: common.CommonResponse
}
var file_idl_interaction_proto_depIdxs = []int32{
	0, // 0: interaction.LikeAuthService.LikeAction:input_type -> interaction.LikeRequest
	1, // 1: interaction.LikeAuthService.GetLikeList:input_type -> interaction.LikeListRequest
	2, // 2: interaction.CommentAuthService.CreateComment:input_type -> interaction.CreateCommentRequest
	4, // 3: interaction.CommentAuthService.DeleteComment:input_type -> interaction.DeleteCommentRequest
	3, // 4: interaction.CommentPublicService.GetCommentList:input_type -> interaction.CommentListRequest
	5, // 5: interaction.LikeAuthService.LikeAction:output_type -> common.CommonResponse
	5, // 6: interaction.LikeAuthService.GetLikeList:output_type -> common.CommonResponse
	5, // 7: interaction.CommentAuthService.CreateComment:output_type -> common.CommonResponse
	5, // 8: interaction.CommentAuthService.DeleteComment:output_type -> common.CommonResponse
	5, // 9: interaction.CommentPublicService.GetCommentList:output_type -> common.CommonResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_interaction_proto_init() }
func file_idl_interaction_proto_init() {
	if File_idl_interaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_interaction_proto_rawDesc), len(file_idl_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_idl_interaction_proto_goTypes,
		DependencyIndexes: file_idl_interaction_proto_depIdxs,
		MessageInfos:      file_idl_interaction_proto_msgTypes,
	}.Build()
	File_idl_interaction_proto = out.File
	file_idl_interaction_proto_goTypes = nil
	file_idl_interaction_proto_depIdxs = nil
}
