// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: idl/interaction.proto

package interaction

import (
	common "github.com/ZOEKOFK/video_web_v3/app/pb/common"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LikeAuthService_LikeAction_FullMethodName  = "/interaction.LikeAuthService/LikeAction"
	LikeAuthService_GetLikeList_FullMethodName = "/interaction.LikeAuthService/GetLikeList"
)

// LikeAuthServiceClient is the client API for LikeAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 点赞服务（需要登录）
type LikeAuthServiceClient interface {
	// 点赞/取消点赞
	// @router /api/likes [POST]
	LikeAction(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
	// 获取点赞列表
	// @router /api/likes/list [GET]
	GetLikeList(ctx context.Context, in *LikeListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
}

type likeAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLikeAuthServiceClient(cc grpc.ClientConnInterface) LikeAuthServiceClient {
	return &likeAuthServiceClient{cc}
}

func (c *likeAuthServiceClient) LikeAction(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, LikeAuthService_LikeAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeAuthServiceClient) GetLikeList(ctx context.Context, in *LikeListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, LikeAuthService_GetLikeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LikeAuthServiceServer is the server API for LikeAuthService service.
// All implementations must embed UnimplementedLikeAuthServiceServer
// for forward compatibility.
//
// 点赞服务（需要登录）
type LikeAuthServiceServer interface {
	// 点赞/取消点赞
	// @router /api/likes [POST]
	LikeAction(context.Context, *LikeRequest) (*common.CommonResponse, error)
	// 获取点赞列表
	// @router /api/likes/list [GET]
	GetLikeList(context.Context, *LikeListRequest) (*common.CommonResponse, error)
	mustEmbedUnimplementedLikeAuthServiceServer()
}

// UnimplementedLikeAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLikeAuthServiceServer struct{}

func (UnimplementedLikeAuthServiceServer) LikeAction(context.Context, *LikeRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeAction not implemented")
}
func (UnimplementedLikeAuthServiceServer) GetLikeList(context.Context, *LikeListRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLikeList not implemented")
}
func (UnimplementedLikeAuthServiceServer) mustEmbedUnimplementedLikeAuthServiceServer() {}
func (UnimplementedLikeAuthServiceServer) testEmbeddedByValue()                         {}

// UnsafeLikeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LikeAuthServiceServer will
// result in compilation errors.
type UnsafeLikeAuthServiceServer interface {
	mustEmbedUnimplementedLikeAuthServiceServer()
}

func RegisterLikeAuthServiceServer(s grpc.ServiceRegistrar, srv LikeAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedLikeAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LikeAuthService_ServiceDesc, srv)
}

func _LikeAuthService_LikeAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeAuthServiceServer).LikeAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeAuthService_LikeAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeAuthServiceServer).LikeAction(ctx, req.(*LikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikeAuthService_GetLikeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeAuthServiceServer).GetLikeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeAuthService_GetLikeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeAuthServiceServer).GetLikeList(ctx, req.(*LikeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LikeAuthService_ServiceDesc is the grpc.ServiceDesc for LikeAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LikeAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.LikeAuthService",
	HandlerType: (*LikeAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LikeAction",
			Handler:    _LikeAuthService_LikeAction_Handler,
		},
		{
			MethodName: "GetLikeList",
			Handler:    _LikeAuthService_GetLikeList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/interaction.proto",
}

const (
	CommentAuthService_CreateComment_FullMethodName = "/interaction.CommentAuthService/CreateComment"
	CommentAuthService_DeleteComment_FullMethodName = "/interaction.CommentAuthService/DeleteComment"
)

// CommentAuthServiceClient is the client API for CommentAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 评论服务（需要登录）
type CommentAuthServiceClient interface {
	// 发表评论
	// @router /api/comments [POST]
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
	// 删除评论
	// @router /api/comments/:comment_id [DELETE]
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
}

type commentAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentAuthServiceClient(cc grpc.ClientConnInterface) CommentAuthServiceClient {
	return &commentAuthServiceClient{cc}
}

func (c *commentAuthServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, CommentAuthService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentAuthServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, CommentAuthService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentAuthServiceServer is the server API for CommentAuthService service.
// All implementations must embed UnimplementedCommentAuthServiceServer
// for forward compatibility.
//
// 评论服务（需要登录）
type CommentAuthServiceServer interface {
	// 发表评论
	// @router /api/comments [POST]
	CreateComment(context.Context, *CreateCommentRequest) (*common.CommonResponse, error)
	// 删除评论
	// @router /api/comments/:comment_id [DELETE]
	DeleteComment(context.Context, *DeleteCommentRequest) (*common.CommonResponse, error)
	mustEmbedUnimplementedCommentAuthServiceServer()
}

// UnimplementedCommentAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommentAuthServiceServer struct{}

func (UnimplementedCommentAuthServiceServer) CreateComment(context.Context, *CreateCommentRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedCommentAuthServiceServer) DeleteComment(context.Context, *DeleteCommentRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedCommentAuthServiceServer) mustEmbedUnimplementedCommentAuthServiceServer() {}
func (UnimplementedCommentAuthServiceServer) testEmbeddedByValue()                            {}

// UnsafeCommentAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentAuthServiceServer will
// result in compilation errors.
type UnsafeCommentAuthServiceServer interface {
	mustEmbedUnimplementedCommentAuthServiceServer()
}

func RegisterCommentAuthServiceServer(s grpc.ServiceRegistrar, srv CommentAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedCommentAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommentAuthService_ServiceDesc, srv)
}

func _CommentAuthService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentAuthServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentAuthService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentAuthServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentAuthService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentAuthServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentAuthService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentAuthServiceServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentAuthService_ServiceDesc is the grpc.ServiceDesc for CommentAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.CommentAuthService",
	HandlerType: (*CommentAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateComment",
			Handler:    _CommentAuthService_CreateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _CommentAuthService_DeleteComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/interaction.proto",
}

const (
	CommentPublicService_GetCommentList_FullMethodName = "/interaction.CommentPublicService/GetCommentList"
)

// CommentPublicServiceClient is the client API for CommentPublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 评论公共服务（无需登录）
type CommentPublicServiceClient interface {
	// 获取评论列表
	// @router /api/videos/:video_id/comments [GET]
	GetCommentList(ctx context.Context, in *CommentListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
}

type commentPublicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentPublicServiceClient(cc grpc.ClientConnInterface) CommentPublicServiceClient {
	return &commentPublicServiceClient{cc}
}

func (c *commentPublicServiceClient) GetCommentList(ctx context.Context, in *CommentListRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, CommentPublicService_GetCommentList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentPublicServiceServer is the server API for CommentPublicService service.
// All implementations must embed UnimplementedCommentPublicServiceServer
// for forward compatibility.
//
// 评论公共服务（无需登录）
type CommentPublicServiceServer interface {
	// 获取评论列表
	// @router /api/videos/:video_id/comments [GET]
	GetCommentList(context.Context, *CommentListRequest) (*common.CommonResponse, error)
	mustEmbedUnimplementedCommentPublicServiceServer()
}

// UnimplementedCommentPublicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommentPublicServiceServer struct{}

func (UnimplementedCommentPublicServiceServer) GetCommentList(context.Context, *CommentListRequest) (*common.CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommentList not implemented")
}
func (UnimplementedCommentPublicServiceServer) mustEmbedUnimplementedCommentPublicServiceServer() {}
func (UnimplementedCommentPublicServiceServer) testEmbeddedByValue()                              {}

// UnsafeCommentPublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentPublicServiceServer will
// result in compilation errors.
type UnsafeCommentPublicServiceServer interface {
	mustEmbedUnimplementedCommentPublicServiceServer()
}

func RegisterCommentPublicServiceServer(s grpc.ServiceRegistrar, srv CommentPublicServiceServer) {
	// If the following call panics, it indicates UnimplementedCommentPublicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommentPublicService_ServiceDesc, srv)
}

func _CommentPublicService_GetCommentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentPublicServiceServer).GetCommentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentPublicService_GetCommentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentPublicServiceServer).GetCommentList(ctx, req.(*CommentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentPublicService_ServiceDesc is the grpc.ServiceDesc for CommentPublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentPublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.CommentPublicService",
	HandlerType: (*CommentPublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCommentList",
			Handler:    _CommentPublicService_GetCommentList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/interaction.proto",
}
